### ISSUE TITLE
Rename items/nametags in scribe table

### ISSUE THREAD

**Issue by ghost** [codetaylor/artisan-worktables#100]
Not sure if this if feasable but it would make sense to be able to (re)name items in the scribe table.

**Comment by codetaylor** [comment]
I like the idea. I'll look into it for a future feature update, thanks. :)

**Comment by codetaylor** [comment]
I have decided against adding this feature because I don't want any inherent table features to nullify, replace, or otherwise compete with vanilla features.

**Comment by VariableVixen** [comment]
I was about to ask about duplicating name tags, but I realised that as long as you can do a recipe function to programatically determine output, you can implement that using marked inputs and copying the NBT tag.
