### ISSUE TITLE
Crash with copied recipes

### ISSUE THREAD

**Issue by azaquaz** [codetaylor/artisan-worktables#101]
#### Issue Description

As far as I can tell, my script is correct. I've replicated the issue with only Artisan Worktables, Athenaeum, and CraftTweaker installed.

#### What Happens

The game crashes when trying to craft a copied recipe on an artisan's table.

#### What You Expect to Happen

I expect the tool to craft normally.

#### Script

https://pastebin.com/9nYmnXpc
This still happens when I change it to have a non-modded item as the result, such as `<ore:stickWood>`.

#### Crash Log

https://pastebin.com/4vPyQmhs

#### Affected Versions
* Minecraft: 1.12.2
* Forge:14.23.2.2641
* CraftTweaker:1.12-4.1.6
* Artisan Worktables:1.12.2-1.18.2
* Athenaeum:1.12.2-1.14.0

**Comment by codetaylor** [comment]
Thanks for the report! :)

Fixed in patch 1.12.2-1.18.3
