### ISSUE TITLE
[1.12.2] Server Crash

### ISSUE THREAD

**Issue by QAngelusQ** [codetaylor/artisan-worktables#104]
#### Issue Description

Server Crash when loading, Client loads fine

#### What Happens

When starting the server after updating to 1.19.0, I get a crash error (linked below)

#### What You Expect to Happen

Server to Load

#### Crash Log

https://pastebin.com/pbD6njrB

#### Affected Versions
* Minecraft: 1.12.2
* Forge: 14.23.2.2611
* CraftTweaker: 1.12-4.1.6
* Artisan Worktables: 1.19.0
* Athenaeum: 1.14.0

**Comment by codetaylor** [comment]
Thanks for the report! :)

Should be fixed in the next alpha snapshot.

**Comment by codetaylor** [comment]
Fixed in 1.12.2-1.19.0-SNAPSHOT.2
