### ISSUE TITLE
Enable usage of RF in workbench.

### ISSUE THREAD

**Issue by talonos2** [codetaylor/artisan-worktables#109]
Suggestion: 
 - If enabled in a config file, and RF meter appears next to the fluid meter in a given crafting table. (Otherwise the RF meter is not present.)
 - Tables can receive RF via other mod's connection methods.
 - Recipes can be set to require a certain amount of RF.
 - Preferably: RF meters are on a per-table basis, so you don't have an RF meter in a scribe's table unless for some reason you really want it. :/

Use case:
 - RF meters would be very useful in recipes in tables such as blacksmith's, chemists, engineers, and maybe even cook's table.

**Comment by Remyrios** [comment]
I feel that it is too much.

**Comment by talonos2** [comment]
It's just a suggested implementation. I guess you could more concisely say "I want to use RF in crafting recipes."

**Comment by codetaylor** [comment]
Thank you for your suggestion! Using RF in crafting recipes would be very useful if that is the kind of pack you are designing, however, I won't be adding this feature to the tables directly. The planned auto-crafting will most likely support RF though.
