### ISSUE TITLE
Request to add a magical worktable.

### ISSUE THREAD

**Issue by renadi** [codetaylor/artisan-worktables#11]
It would be fun to have a magical worktable for a bunch of the items in vanilla that don't really fit fully into other tables, it could use a tool like a magic wand or some kind of gem focus perhaps(seems like this would go against the theme of using the metals, and be fairly limiting in a vanilla-ish world, but in a modpack there are often dozens of gems that could be used).

**Comment by codetaylor** [comment]
I plan to add at least two more tables in the future. I really like the idea you present and I will include a magical table when I add more tables. Thanks! :)

**Comment by codetaylor** [comment]
Coming soon(tm)!

![2018-01-11_17 37 04](https://user-images.githubusercontent.com/1240716/34855809-9611423a-f6f6-11e7-84d2-aa442fb32ece.png)

**Comment by codetaylor** [comment]
Available in 1.12.2-1.7.10
