### ISSUE TITLE
OreDict for the table?

### ISSUE THREAD

**Issue by Nitess** [codetaylor/artisan-worktables#110]
Hi, I'm doing modpack, and I did not find OreDict for the table. There are levels, but no oredict. I would like players to use any table to create. Can this be realized?
RecipeBuilder.get("basic") may be RecipeBuilder.get("all")

but without displaying all kinds of workbenches in jei
![2018-04-28 18-29-14 minecraft 1 12 2 2](https://user-images.githubusercontent.com/30369743/39398146-6e716d84-4b12-11e8-988a-4555ee12699a.png)

**Comment by codetaylor** [comment]
I can probably implement `RecipeBuilder.get("all")`, but it will display all the workbenches in JEI; that's just how it works.

**Comment by Nitess** [comment]
then it is not possible to do so that the recipes would work on all workbenches?

**Comment by codetaylor** [comment]
Not right now, no.

You could write a function in CrT to do it though, something like this (pseudocode):

```
var tables = [
  "blacksmith",
  "tanner",
  ...
]

function setShaped(output, recipe, tool, damage) {
  for table in tables {
    RecipeBuilder.get(table)
      .setShaped(recipe)
      .addTool(tool, damage)
      .addOutput(output)
      .create();
  }
}
```
