### ISSUE TITLE
Client Crash with GameStages 2.0 Update

### ISSUE THREAD

**Issue by QAngelusQ** [codetaylor/artisan-worktables#111]
The Game client crashes with the newest 2.0 update with GameStages. 

The Server is fine and goes through perfectly. 

Client Crash Report: https://pastebin.com/h5Vas1p7

* Minecraft: 1.12.2
* Forge: 14.23.3.2655
* CraftTweaker: 4.1.8
* Artisan Worktables: 1.19.0-SNAPSHOT.3
* Athenaeum: 1.14.0

* GameStages: 2.0.90

**Comment by codetaylor** [comment]
Thanks for the report!

Fixed in stable beta branch: 1.12.2-1.18.5

Will also be merged and fixed in next alpha snapshot.

**Comment by codetaylor** [comment]
Fixed in alpha 1.12.2-1.19.0-SNAPSHOT.4
