### ISSUE TITLE
JEI screens are empty

### ISSUE THREAD

**Issue by hron84** [codetaylor/artisan-worktables#114]
#### Issue Description

I making a private modpack based on your worktables, in fact, I heavily depend on them with the current progression line. Previously everything worked correctly however (I think after a JEI update) all JEI screens went blank. I downgraded to 1.18.3 but did not solved the problem.

I'm not too well-informed about how JEI works so please bear with me and let me know step-by-step what can I do in this situation.

**EDIT**

After I downgraded JEI to 4.9.1.187, it works again.

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 2678
* CraftTweaker: 4.1.8
* Artisan Worktables: 1.18.3
* Athenaeum: 1.14.0
* JEI: 4.9.1.188

![2018-05-22_23 32 25](https://user-images.githubusercontent.com/88636/40391594-20c348b8-5e19-11e8-9592-5ced0e51d8c6.png)

**Comment by codetaylor** [comment]
Looks like the only difference between 188 and 187 is:

```
Filter out hidden ingredients from recipe rotations where possible
```

It corresponds with this commit: https://github.com/mezz/JustEnoughItems/commit/bd8ff72d0ded0cc90e715b5c476586b9acd879af

I will have more time to look into this tomorrow.

**Comment by codetaylor** [comment]
It looks like I was passing a null fluid into JEI for recipes that didn't have fluids and the update from 187 to 188 no longer silently handles nulls - it now throws a NPE. Throwing a null check around those seemed to fix the issue.

This fix will be available in the stable beta branch as well as the alpha snapshot branch later today.
