### ISSUE TITLE
Psuedo-Shaped Recipes

### ISSUE THREAD

**Issue by IronPiston** [codetaylor/artisan-worktables#115]
I was adding a recipe for TiC seared bricks, and realized that due to the 2x2 crafting recipe, I would have to add in 3 other permutations to allow the recipe to be crafted in each corner of the grid. This issue is further exasperated in the 5x5 crafting grid, when the recipe would have to be repeated countless times. Perhaps a recipe in a grid bigger than it could be craft-able in any section.

For example, a 2x2 crafting recipe would be able to work anywhere on the 3x3 grid, as long as the original recipe was retained. This could apply to a 3x3 recipe in the worktable as well.
![2018-05-24_00 21 03](https://user-images.githubusercontent.com/11603684/40466009-3cf09a92-5ee9-11e8-9d7a-b24c389a5b5d.png)
![2018-05-24_00 24 26](https://user-images.githubusercontent.com/11603684/40466012-3f387496-5ee9-11e8-88ff-c3d014549d22.png)

**Comment by codetaylor** [comment]
It has always worked that way. Please ensure your recipes don't have any `null` around the edges.

```javascript
import mods.artisanworktables.builder.RecipeBuilder;

RecipeBuilder.get("carpenter")
	.setShaped([
	    [<ore:plankWood>, <ore:plankWood>],
	    [<ore:plankWood>, <ore:plankWood>]
	])
	.addTool(<ore:artisansFramingHammer>, 1)
	.addOutput(<minecraft:string>)
	.create();
```

![2018-05-24_05-59-50](https://user-images.githubusercontent.com/1240716/40487053-d7275820-5f17-11e8-9c1e-73de3fbcccbb.gif)

**Comment by IronPiston** [comment]
Yeah, I surrounded the recipe with nulls. Thanks!
