### ISSUE TITLE
Copy.ByName Isn't working for modded items

### ISSUE THREAD

**Issue by thehowlinggreywolf** [codetaylor/artisan-worktables#116]
#### Issue Description

The issue appears when using the .setCopy(Copy.ByName string) function. When using a modded items name as the string, the script produces no errors but also produces no recipe. When changing to use a vanilla item, the recipe does get created.

#### What Happens

I have been able to reproduce this with both my own script below and also the example script provided on the read the docs, by changing the output to any modded item no recipe is created.

#### What You Expect to Happen

I expect there to be a recipe output for modded items, and if this is not implemented then it would be nice to have the docs state this.

#### Script

This is the full worktables script:

https://pastebin.com/s72aH8kW

This is the part of the script that appears to have no effect:

https://pastebin.com/s72aH8kW

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.3.2698
* CraftTweaker: 4.1.8
* Artisan Worktables: 1.18.6 AND 1.19.0-SNAPSHOT.5
* Athenaeum: 1.14.0

**Comment by codetaylor** [comment]
`Copy.byName` works with recipe *names*, as stated in the docs. What you have, `betterwithmods:material:34`, isn't a recipe name. The recipe name for that item is `betterwithmods:items/material/material.redstone_latch`.

To find recipe names, use the advanced tooltips `F3 + H` and hover over the output item in JEI. The recipe name will be displayed at the bottom of the tooltip after `Recipe ID:`.
