### ISSUE TITLE
Game crashes on load

### ISSUE THREAD

**Issue by Priderino** [codetaylor/artisan-worktables#117]
The game crashes when i mess with the config files. Also, for some reason it crashes when I disable the Mechanical Toolbox on the config.
Version: AW 1.18.6
Athenaem: 1.14.0
Forge: 14.23.4.2705

https://pastebin.com/bx2DTghD
[Artisan Worktables Config.zip](https://github.com/codetaylor/artisan-worktables/files/2055923/Artisan.Worktables.Config.zip)

**Comment by codetaylor** [comment]
```
com.google.gson.stream.MalformedJsonException: Unterminated object at line 15 column 8 path $.list[0].oreDictKey
```

Looks like you've got some invalid json.

The only json file that would cause that is:

```
artisanworktables.module.Tools.Materials.Custom.json
```

I'd check that.

Also, in the future, please use pastebin, gist, or an alternative to post your config files.

**Comment by Priderino** [comment]
I've remade the config files and was able to fix the crash. But yeah, my bad on the config files.
