### ISSUE TITLE
Cannot put tools in tool slots 

### ISSUE THREAD

**Issue by Rosethorns** [codetaylor/artisan-worktables#119]
#### Issue Description

No matter what I do. try to place the tool in the tool slot, try to right click the table with the tool. hopper the tool in from various sides, I just can't seem to get the tools in the table. Can't seem to find any documentation around this either so I feel real stupid if its something obvious.

#### What Happens

I created a recipe for a door (pictured below)
![image](https://user-images.githubusercontent.com/2171914/40760619-a5beae12-64eb-11e8-9a85-42afce4918d6.png)

As you can see the tools appear correctly assigned in the recipe.
(script linked in relevant form section)
How ever when I attempt to place the required tools in the tool slot of the table.
![image](https://user-images.githubusercontent.com/2171914/40760701-1b2f49ae-64ec-11e8-936a-acd6d3ef73da.png)
It just won't take the tools.
I have tried checking all the documentation and I am sorry if missed the obvious. 

#### What You Expect to Happen

to be able to put accepted tools in the tool slot of the table

#### Script

https://pastebin.com/xWW42C04

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.4.2705
* CraftTweaker: 4.1.8
* Artisan Worktables: 1.19.0-SNAPSHOT.5
* Athenaeum: 1.14.0

**Comment by Rosethorns** [comment]
I'm an idiot. Wrong table defined.

**Comment by codetaylor** [comment]
No worries. :)
