### ISSUE TITLE
Issue when crafting item with weighted primary output

### ISSUE THREAD

**Issue by Bulldog83** [codetaylor/artisan-worktables#124]
#### Issue Description

When I try to craft item with weighted primary output this don't support shift+click craft and don't stacks output items in the hand, but inputs are expended and in the hand remains the result of only the last crafting.

```
RecipeBuilder.get("mason")
	.setShapeless([<minecraft:stone>])
	.addOutput(<primal:rock_stone> * 4, 15)
	.addOutput(<primal:rock_stone> * 3, 85)
	.setExtraOutputOne(<minecraft:gravel>, 0.1)
	.addTool(<ore:artisansHammer>, 2)
	.create();
```

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.4.2705
* CraftTweaker: 4.1.9
* Artisan Worktables: 1.19.0-SNAPSHOT.8
* Athenaeum: 1.14.0

**Comment by codetaylor** [comment]
By design, shift+click is restricted for recipes with multiple, chanced outputs. See [this discussion](https://github.com/codetaylor/artisan-worktables/issues/18#issuecomment-357824105) to see why.

I'm looking into the craft eating input items.
