### ISSUE TITLE
Restricting entire mod's crafting recipes to table

### ISSUE THREAD

**Issue by Konclan** [codetaylor/artisan-worktables#128]
I don't know where to ask questions about the mod. Please tell if there if there is a better place for these like a forum or discord for this.

What is the best method to take recipes from an entire mod and move it to a certain worktable?

**Comment by codetaylor** [comment]
* Iterate through recipes for the mod
* For each, use AW's copy to copy the recipe
* For each, remove recipe

https://crafttweaker.readthedocs.io/en/latest/#

https://artisan-worktables.readthedocs.io/en/latest/

There's also the CraftTweaker discord - lots of knowledgeable people over there.
