### ISSUE TITLE
Copied recipes are all shapeless

### ISSUE THREAD

**Issue by Konclan** [codetaylor/artisan-worktables#129]
When I copy all the recipes from a mod over to a worktable, they are all shapeless reguardless if the original recipe was shaped or not.

Perhaps its the way I'm doing it and perhaps its not possible to tell if the recipe was shapped or not. Is there a way to make the copied recipe shaped without changing it.

script: https://pastebin.com/WVcfvVcT

* Minecraft: 1.12.2
* Forge: 14.23.4.2757
* CraftTweaker: 1.12-4.1.9
* Artisan Worktables: 1.12.2-1.18.11
* Athenaeum: 1.12.2-1.14.0

**Comment by codetaylor** [comment]
I've used the copy feature with many mods and I am unable to reproduce the issue. This mod should be able to distinguish between shaped and shapeless recipes using `instanceof IShapedRecipe`. My guess is that the mod in question does not extend `IShapedRecipe` for its shaped recipes.

**Comment by codetaylor** [comment]
Nevermind, I was able to reproduce it using:

```js
import mods.artisanworktables.builder.RecipeBuilder;
import mods.artisanworktables.builder.Copy;

val builder = RecipeBuilder.get("engineer");

for recipe in recipes.getRecipesFor(<minecraft:furnace>) {
    builder
        .setCopy(Copy.byRecipe(recipe))
        .addTool(<artisanworktables:artisans_hammer_steel>, 1)
        .create();
}
```
