### ISSUE TITLE
Vertical sheped recipes bug

### ISSUE THREAD

**Issue by Smartaros** [codetaylor/artisan-worktables#13]
For example:
`Worktable.addRecipeShaped("carpenter", <quark:vertical_planks> * 3, <ore:carpenters_hammer>, 3, false, 
    [[<minecraft:planks>], [<minecraft:planks>], [<minecraft:planks>]]);`
must be a "vertical", but it is "horizontal"

**Comment by codetaylor** [comment]
What version of the mod are you using?

**Comment by Smartaros** [comment]
1.4.8
  my bad

**Comment by codetaylor** [comment]
I'm using 1.5.9 and seems to work fine.

JEI:
![image](https://user-images.githubusercontent.com/1240716/34647036-ef3ebfdc-f32b-11e7-85bf-e8828f0534cb.png)

Crafting:
![image](https://user-images.githubusercontent.com/1240716/34647038-103c1a40-f32c-11e7-85f5-6f0084571089.png)

**Comment by codetaylor** [comment]
I just fixed a bug with JEI recipes displaying shaped recipes as shapeless about an hour ago in issue #12.

This might be the issue you're experiencing.
