### ISSUE TITLE
[Question] Automatic Naming

### ISSUE THREAD

**Issue by NielsPilgaard** [codetaylor/artisan-worktables#130]
#### Intro

Please follow the template when submitting an issue.

If you are submitting a suggestion, feature request, or idea, please delete this template and follow the guidelines found in the README.md file.

If you do not follow the template or guidelines, your issue will be flagged as `invalid` and may be immediately closed.

Text placed within *[replace]* tags may be omitted and replaced with your text.

#### Issue Description

I have made several AW recipes that take Wood Logs as input and make varying amounts of planks. 
The amount of planks given depends on the crafter's gamestage. 
Due to the output and input being the same in multiple recipes, the recipes are given the same names, and the chat is spammed with `Duplicate recipe name found: carpenter:[number]`. Is there any way to force AW to use different names, or something similar? I have not been able to turn off error logging to prevent the output.

Since this is not a bug, I will leave some fields empty, I hope that's alright.

#### Script

https://hastebin.com/julerabeti.bash

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.4.2758
* CraftTweaker: 1.12-4.1.9
* Artisan Worktables: 1.12.2-1.19.0-SNAPSHOT.10
* Athenaeum: 1.14.0

**Comment by NielsPilgaard** [comment]
I discovered the `.setName(string)` function. Would you mind adding that to the [Quick Reference](https://artisan-worktables.readthedocs.io/en/latest/recipes/quickreference/#zenscript-methods)?

However, I think the auto generated name should be unique, even if the recipes are very similar, have you considered using Cryptographic Hashing for naming, like (I believe) CraftTweaker does?

**Comment by codetaylor** [comment]
The recipe naming is described in the alpha docs. It will be merged with the main docs when/if the feature leaves alpha.

https://artisan-worktables.readthedocs.io/en/release-next/recipes/names/
