### ISSUE TITLE
setMirrored() Issue

### ISSUE THREAD

**Issue by NielsPilgaard** [codetaylor/artisan-worktables#131]
#### Issue Description

Using `.setMirrored()` doesn't correctly mirror the recipe.
Here's an example of a recipe I want to mirror, where 2 planks give 4 slabs.
Plank = X
Null = 0

X X 0
0 0 0
0 0 0

Using setMirrored on that recipe, is supposed to make the recipe work in all sorts of places, but what it actually accepts is:

X X 0
0 0 0
0 0 0

and

0 X X
0 0 0
0 0 0

Meaning I have to make the additional recipes like so:

0 0 0
X X 0
0 0 0

for mirrored to work correctly.

#### What Happens

Described in issue.

#### What You Expect to Happen

I expected the recipe to work in 6 different places

#### Script

https://hastebin.com/foyiheyaco.coffeescript

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

    Minecraft: 1.12.2
    Forge: 1.12.2-14.23.4.2758
    CraftTweaker: 1.12-4.1.9
    Artisan Worktables: 1.12.2-1.19.0-SNAPSHOT.10
    Athenaeum: 1.14.0

**Comment by codetaylor** [comment]
You are restricting the pattern placement with all the nulls and you don't need mirrored to do what you want.

Do this instead:

```javascript
RecipeBuilder.get("carpenter")  
  .setShaped([
        [<minecraft:planks>, <minecraft:planks>]
        ])
  .addTool(<ore:artisansFramingHammer>, 8)
  .addOutput(<tconstruct:rack>)
  .addRequirement(GameStages.anyOf(["novice_carpenter"]))
  .setName("tconstruct_item_rack_")
  .create();
```

**Comment by NielsPilgaard** [comment]
Oh I see, thank you :)
