### ISSUE TITLE
Recipes no longer copied after CraftTweaker updating

### ISSUE THREAD

**Issue by Bulldog83** [codetaylor/artisan-worktables#132]
#### Issue Description

After the last update of CraftTweaker, the recipes for items that were deleted through the recipes.remove(IItemStack) no longer copied via Copy.

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.4.2747
* CraftTweaker: 4.1.10
* Artisan Worktables: 1.19.0-SNAPSHOT.10 (1.18.11-75-g284910e)
* Athenaeum: 1.14.0

**Comment by codetaylor** [comment]
I'm pretty sure this commit is the culprit: https://github.com/CraftTweaker/CraftTweaker/commit/957e0034580d8761538aeb80e71e97515f4603e4.

I'll look into this soon.

**Comment by Bulldog83** [comment]
I have 2 mods whose recipes are still not copied: PrimalCore and EnderIO. Recipes are not copied nor byName, nor byOutput or byRecipes. I think that these mods are add recipes after copying, but before they are removed by CraftTweaker. Since recipes are deleted, but not copied.

**Comment by codetaylor** [comment]
I was afraid of that.

I used an ugly hack to ensure that my copy code was run at the latest possible moment, immediately before CrT removes recipes. Due to the commit mentioned above, I can no longer do that.

**Comment by Bulldog83** [comment]
I'm not shure, but may be you can use this mechanics of last CraftTweaker?
> "Loaders now can be delayed/frozen until the mod that froze them calls the frozen alias. This should allow for mods to prevent a loader from being loaded to early by other mods. They now need to subscribe to the load_finished event, if they want to get the post-finished loader stage though."

**Comment by codetaylor** [comment]
Thank you, but unfortunately, no, this isn't a loader issue.

**Comment by codetaylor** [comment]
This is fixed an will be available in the next release.

Because it requires CraftTweaker >= 4.1.11.500, I must wait until the new version of CrT is uploaded to Curse before I can release.
