### ISSUE TITLE
Tinkers Construct Compatibility

### ISSUE THREAD

**Issue by Burgersim** [codetaylor/artisan-worktables#137]
I don't know if this really falls under suggestion, i think it would more be a question in general.

I really like the idea of this mod and the worktables, so I was tinking, firstly, are the Tinkers Construct Materials already in the game? And secondly, would there be an "easy" way to use these tables instead of Tinker's Construct ones, but still create the Tools from Tinkers Construct? I would love to have a modpack, that takes some of the complexity of Tinker's Construct out but still has these awesome Tools and all the possibilities. 

So my suggestion would be, or question, is there a way for "easy" compatibility with Tinker's Construct? Being able to generate the recipes for all the Tools, Materials and Stuff but using these Tables?

**Comment by codetaylor** [comment]
> ...are the Tinkers Construct Materials already in the game?

What?

> And secondly, would there be an "easy" way to use these tables instead of Tinker's Construct ones, but still create the Tools from Tinkers Construct?

No...

> So my suggestion would be, or question, is there a way for "easy" compatibility with Tinker's Construct? 

No.

> Being able to generate the recipes for all the Tools, Materials and Stuff but using these Tables?

No.

**Comment by Burgersim** [comment]
Hmm well too bad, but thx for the quick answer anyways ^^

**Comment by Burgersim** [comment]
Oh wait, I have another question though, is it possible to just let one table use, say all vanilla (tool) recipes or would you have to manually add every recipe to a table?

**Comment by codetaylor** [comment]
You'll have to add them.

You can use the copy stuff to make it easier: https://artisan-worktables.readthedocs.io/en/latest/recipes/copying/
