### ISSUE TITLE
Designer tools

### ISSUE THREAD

**Issue by josephcsible** [codetaylor/artisan-worktables#139]
Looking in [EnumWorktableToolType.java](https://github.com/codetaylor/artisan-worktables/blob/48e30210f5bc5f0313377e0c66b345a6522b4ee0/src/main/java/com/codetaylor/mc/artisanworktables/modules/tools/reference/EnumWorktableToolType.java), there appear to be no tools made for the designer tables, unlike all of the others (slightly cheating by counting "universal" as "basic"). Will tools be forthcoming for this table, or is it going to be special-purpose unlike the rest of the tables such that it wouldn't make sense to have tools of its own?

**Comment by codetaylor** [comment]
Yeah, maybe a pencil and square. What did you have in mind?

**Comment by josephcsible** [comment]
I didn't really have anything specific in mind, so I guess just go with those.
