### ISSUE TITLE
Exception in server Tick loop

### ISSUE THREAD

**Issue by MasterEnderman** [codetaylor/artisan-worktables#141]
#### What Happens

The game crashes after entering a new world.

#### Crash Log

https://paste.dimdev.org/igomonijec.mccrash

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 14.23.5.2784
* CraftTweaker: 4.1.13
* Artisan Worktables: 1.19.3
* Athenaeum: 1.14

**Comment by codetaylor** [comment]
This is completely my fault, I'm sorry. I compiled against a version of my lib that isn't released yet.

To fix this, I will release an updated version of the lib and release a new version of AW that requires the correct lib version.

Again, sorry for the hassle.

**Comment by codetaylor** [comment]
Should be fixed in 1.12.2-1.19.4

Please also update Athenaeum to 1.12.2-1.15.0
