### ISSUE TITLE
Crash with Immersive Engineering

### ISSUE THREAD

**Issue by MasterEnderman** [codetaylor/artisan-worktables#142]
#### What Happens

Crash when entering a world.

#### Crash Log

https://paste.dimdev.org/arinatajic.mccrash

#### Affected Versions

*Minecraft: 1.12.2
*Forge: 14.23.5.2784
*CraftTweaker: 4.1.13
*Artisan Worktables: 1.19.3
*Athenaeum: 1.14
*Immersive Engineering: 0.12-86

**Comment by codetaylor** [comment]
This crash is happening for the same reason as #141, so I'm going to close this and work off of that one.
