### ISSUE TITLE
Recipe has valid syntax but CT isn't loading it.

### ISSUE THREAD

**Issue by MarkMaurer1427** [codetaylor/artisan-worktables#143]
Recipe has valid syntax but CT isn't loading it.

I'm trying to make recipes that use the mortar to break down ores, but despite a check with "/ct syntax" saying the code is correct I'm getting an error message that I can't trace back to anything.

Error message: https://pastebin.com/U02uy66q

This appears when I load a world, and the recipe doesn't work. /ct syntax says it's correct, but something else appears to be a problem.

I expected to be able to use a mortar to break iron ore on a basic table

CT recipe script: https://pastebin.com/fVZgmLWW
Global variable script: https://pastebin.com/x4BxaP6b

The world DOES load, but the recipe fails to load.

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2768
* CraftTweaker: 4.1.13
* Artisan Worktables: 1.12.2-1.19.4
* Athenaeum: 1.12.2-1.15.0

**Comment by codetaylor** [comment]
What happens if you replace the globals with their actual values in the recipe script?

**Comment by MarkMaurer1427** [comment]
It worked when I used the values, so the issue is that it's not pulling them from globals.
