### ISSUE TITLE
Random Output Recipe Malfunction

### ISSUE THREAD

**Issue by NielsPilgaard** [codetaylor/artisan-worktables#144]
#### Issue Description

I've made a recipe with multiple possible outputs, with the same weight. The recipe loads, however I'm unable to actually use the recipe. In addition, the output item has no name when I hover over it in the JEI recipe view.

#### What Happens

A recipe doesn't work.

#### What You Expect to Happen

The recipe to work, with the output being randm.

#### Script

https://gist.github.com/NillerMedDild/df1a0e5f474ddc37c3687f5f730ee8c9

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 1.12.2-14.23.5.2795
* CraftTweaker: 1.12-4.1.13
* Artisan Worktables: 1.12.2-1.19.4
* Athenaeum: 1.12.2-1.15.0

**Comment by NielsPilgaard** [comment]
Images:
![billede](https://user-images.githubusercontent.com/21295394/49648859-adb83800-fa27-11e8-8ff8-4e08ec34ea53.png)
![billede](https://user-images.githubusercontent.com/21295394/49648866-b446af80-fa27-11e8-966c-9f71b5c64ee1.png)
![billede](https://user-images.githubusercontent.com/21295394/49648876-bad52700-fa27-11e8-8049-7dc481239238.png)

**Comment by codetaylor** [comment]
Hi, thanks for the report!

It looks like you have two items in your output that have the wrong name.

I changed

```
  .addOutput(<minecraft:carrots>)
  .addOutput(<minecraft:potatoes>)
```

... to ...

```
  .addOutput(<minecraft:carrot>)
  .addOutput(<minecraft:potato>)
```

... and everything works as expected.

I don't know why CrT didn't report any errors though.

**Comment by codetaylor** [comment]
I'm adding in some checks that will invalidate recipes with empty input / output and print to the CrT log:

```
[INITIALIZATION][CLIENT][ERROR] Output can't be empty (issue144.zs:3)
[INITIALIZATION][CLIENT][ERROR] Output can't be empty (issue144.zs:3)
[INITIALIZATION][CLIENT][ERROR] Failed to create recipe (issue144.zs:3)
[INITIALIZATION][CLIENT][ERROR] Invalid recipe (issue144.zs:3)
```

**Comment by NielsPilgaard** [comment]
Thank you!
