### ISSUE TITLE
Slots for consumables

### ISSUE THREAD

**Issue by Smartaros** [codetaylor/artisan-worktables#147]
For it to be like a reservoir for liquids, but only as slots for items. Using these slots you can create more realistic recipes, like crafting something wooden, comsume nails on it. It would also be very helpful if there is already a 3x3 recipe (or 5x5), but which seems incomplete, for example, the craft of some device takes up the entire grid of the workbench, and from these additional slots could take bolts with nuts. (sorry for my English)

**Comment by codetaylor** [comment]
There are an additional 9 slots provided for a 'reservoir' of items in the workstation and workshop tables called [Secondary Ingredients](https://artisan-worktables.readthedocs.io/en/latest/recipes/secondaryingredients/). These slots will hold any item and recipes can be configured to consume any number of items from these slots.

**Comment by Smartaros** [comment]
well, it's gorgeous ... I thought it was just an inventory ... I apologize for the inattention
