### ISSUE TITLE
Add all recipes from vanilla crafting table

### ISSUE THREAD

**Issue by hron84** [codetaylor/artisan-worktables#148]
It would be awesome if somehow we can configure any table (preferably the basic table) to act as vanilla crafting table. Since Artisan tables can hold items when GUI is closed, it would be good for packs that do not want to add mods only for this behavior but let player craft a basic crafting table and use it as an enhanced vanilla one.

I know it could be a headache since there is a lot of recipe handlers that may break in your tables, but it would be nice if you at least investigate this possibility.

**Comment by codetaylor** [comment]
I will definitely take a look when I dive into the automation stuff.

**Comment by Xorbah** [comment]
I second this. Would be highly useful for mods such as From The Ground Up.

**Comment by codetaylor** [comment]
This is implemented in-dev and will be available in `1.22.0`

The config will have a list like so:

```
    # Tables in this list will allow crafting any of the vanilla recipes.
    # Table id format is (type):(tier)
    # By default, all tables are allowed.
    S:ENABLE_VANILLA_CRAFTING <
        basic:workshop
        basic:workstation
        basic:worktable
        blacksmith:workshop
        blacksmith:workstation
        blacksmith:worktable
        ...
        >
```

**Comment by VariableVixen** [comment]
This is similar to a pack I'm working on, where _no_ vanilla crafting is possible. At all. Every single crafting table recipe is going to be moved to an appropriate table with the relevant tools.

My problem so far is figuring out how to _get_ you the table and the initial basic tools without allowing vanilla crafting...

**Comment by hron84** [comment]
Thanks! It's so nice! ❤️
