### ISSUE TITLE
JEI "+" Voiding items in Artisan Worktable

### ISSUE THREAD

**Issue by Vyraal1** [codetaylor/artisan-worktables#149]
#### Issue Description
Using JEI's "+" button and shifting to move entire stacks will void items instead of moving them into the Artisan Worktable.

Video: https://streamable.com/6wvor

#### What Happens

Items are voided.

#### What You Expect to Happen

The table to be populated appropriately. 

#### Script

https://gist.github.com/Vyraal1/4dc5f275e0746dae6bbcd7036a008258

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 2784
* CraftTweaker: 1.12-4.1.13
* Artisan Worktables: 1.20.0
* Athenaeum: 1.15.0
* **JEI**: 4.14.4.257

**Comment by codetaylor** [comment]
It looks the JEI code for recipe transfers has changed since my PR in December of 2017: https://github.com/mezz/JustEnoughItems/commits/1.12/src/main/java/mezz/jei/transfer/BasicRecipeTransferHandlerServer.java

I'll bet the culprit lies within those changes.

**Comment by codetaylor** [comment]
There's an issue on JEI's tracker: https://github.com/mezz/JustEnoughItems/issues/1464

**Comment by codetaylor** [comment]
I have located the issue and submitted a PR: https://github.com/mezz/JustEnoughItems/pull/1466

For more information, please refer to this issue on JEI's tracker: https://github.com/mezz/JustEnoughItems/issues/1464

**Comment by Vyraal1** [comment]
Closing this one and waiting on JEI, thanks again!
