### ISSUE TITLE
Shifting clicking output slot Ignores Astral Progression Deteection

### ISSUE THREAD

**Issue by Vyraal1** [codetaylor/artisan-worktables#150]
#### Issue Description

*[replace]*

If this issue occurs in a modpack, please report this to the modpack author. Also, please take the time to look at existing issues to ensure you don't create a duplicate. You may remove this line and place your issue description here.

*[/replace]*

#### What Happens

Shift clicking the output seems to ignore the astral sorcery progression detection, whereas normal clicking is still detected just fine.
https://streamable.com/8yvbi

#### What You Expect to Happen
Astral progression to be detected.

#### Script
```
RecipeBuilder.get("basic")
	.setShaped([
		[<ore:stoneMarble>, sootyMarble, <ore:stoneMarble>],
		[<ore:stoneMarble>, <minecraft:crafting_table>, <ore:stoneMarble>],
		[<ore:stoneMarble>, null, <ore:stoneMarble>]])
	.setFluid(<liquid:mana_fluid> * 2000)
	.addTool(<ore:toolSaw>, 40)
	.addOutput(<astralsorcery:blockaltar>)
	.create();
```

#### Affected Versions
* Minecraft: 1.12.2
* Forge: 2784
* CraftTweaker: 4.1.13
* Artisan Worktables: 1.20.0
* Athenaeum: 1.15.0

**Comment by codetaylor** [comment]
Should be fixed in version 1.12.2-1.20.1

Please let me know if it doesn't work, thanks!
