### ISSUE TITLE
JEI and Artisan Worktables

### ISSUE THREAD

**Issue by MineplayerHDYT** [codetaylor/artisan-worktables#152]
#### Issue Description

When i want to view a recipe from Artisan Worktables the game crashes.
A Mod tells me that its the fault of JEI.

#### What Happens

When i use a newer/ the newest version of forge and JEI the game crashes when i want to view a recipe of Artisan Worktables.
When i downgrade the JEI and Forge it works.
Steps:
Download newest version of Artisan Worktables and JEI
Create a recipe and try to view it via. JEI
crash

#### What You Expect to Happen

that the JEI works and shows the recipe

#### Script

/

#### Crash Log

https://paste.dimdev.org/yerewabuxo.mccrash

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 14.23.5.2768 and up
* CraftTweaker: /
* Artisan Worktables: 1.20.1
* Athenaeum: 1.16.0

**Comment by codetaylor** [comment]
Please provide JEI version that crashes and JEI version that does not crash.

**Comment by MineplayerHDYT** [comment]
Well when its forge up the version 14.23.5.2768 every JEI version crashes 
when its under 14.23.5.2768 or 14.23.5.2768 it will work
it is the fault of the forge version

**Comment by MineplayerHDYT** [comment]
so can you do something to fix this?

**Comment by codetaylor** [comment]
I am unable to reproduce this crash using only the following:
  * Forge: 14.23.5.2811
  * Athenaeum: 1.12.2-1.16.0
  * Artisan Worktables: 1.12.2-1.20.1
  * JEI: 1.12.2-4.14.4.264
  * CraftTweaker: 1.12-4.1.14

This indicates to me that the crash is being caused by the presence of another mod.

**Comment by MineplayerHDYT** [comment]
there is a crashlog

**Comment by MineplayerHDYT** [comment]
could it be a fault of JEI Integration?

**Comment by codetaylor** [comment]
No, the crash is most likely the cause of another mod entirely, like a core mod. Disable mods one at a time until the crash stops, then you will know which one is causing it. I would start with the core mods.

**Comment by MineplayerHDYT** [comment]
okay thank you
