### ISSUE TITLE
Leatherworks Tannin Integration Issue (Fluids)

### ISSUE THREAD

**Issue by BraniyaKz** [codetaylor/artisan-worktables#153]
#### Intro

So I'm making a mod pack that involves leatherworks and artisan worktables.
I wanted to fill the tanner workstation with tannin from leatherworks.
It can no do.

#### Issue Description

So I tried adding an example script to see if it would register.

#### What Happens

It didn't. Tannin still doesn't go into internal workstation's tank.

#### What You Expect to Happen

I was hoping the workstations and workshops could accept custom liquids. Is this a Leatherworks problem, or an Artisan Worktables thingamabob?

#### Script

It's only a test script:
https://pastebin.com/NLhmEvZ6

#### Crash Log

No crash.

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2810
* CraftTweaker: 4.1.14
* Artisan Worktables: 1.20.1
* Athenaeum: 1.16.0-1 g05e9939

**Comment by codetaylor** [comment]
It works with all fluids.

Does your `crafttweaker.log` report any errors? I notice that the syntax of the script is not correct.

There is a `.` missing between `RecipeBuilder` and `get("tanner")` and there is a `;` at the end of the same line. This is what it should look like:

```
import mods.artisanworktables.builder.RecipeBuilder;

RecipeBuilder.get("tanner")
	.setShapeless([<minecraft:dirt>])
	.setFluid(<liquid:tannin> * 1000)
	.addOutput(<minecraft:cobblestone>)
	.create();
```
