### ISSUE TITLE
Repair manasteel, elementium, and terrasteel tools with mana

### ISSUE THREAD

**Issue by codetaylor** [codetaylor/artisan-worktables#155]
I would like the option to repair manasteel, elementium, and terrasteel tools with mana.

**Comment by mrdeadlocked** [comment]
This would be fantastic!

**Comment by Steamoonkie** [comment]
@codetaylor This wouldnt be any help for you, right?
https://minecraft.curseforge.com/projects/manatweaks

**Comment by codetaylor** [comment]
This has been implemented and will be available in the mod Artisan Integrations when it is released.

When crafting with a tool made from a Botania metal, the player's mana will be consumed before damaging the tool. There is also a config option to turn off consuming the player's mana.
