### ISSUE TITLE
Right-clicking output only gives half of the stack

### ISSUE THREAD

**Issue by Vyraal1** [codetaylor/artisan-worktables#156]
#### Issue Description

Right clicking on artisan worktable output with an itemstack greater than 1 only gives you half of the crafted output. 

#### What Happens

Recipe for any itemstack greater than 1 only gives half if right clicked out of the output.

#### What You Expect to Happen

It would provide the full amount as dictated by the recipe

#### Script

https://pastebin.com/s8CVrqcd

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 2795
* CraftTweaker: 4.1.17
* Artisan Worktables: 1.20.1
* Athenaeum: 1.16.0-1-g05e9

**Comment by codetaylor** [comment]
Thanks for the report!

Fixed in version 1.12.2-1.20.2
