### ISSUE TITLE
Disabling modules Toolbox and Tools doesn't do anything

### ISSUE THREAD

**Issue by Alicegamergirl** [codetaylor/artisan-worktables#158]
#### Issue Description

Disabling modules **Toolbox** and **Tools** doesn't do anything.

#### What Happens

All the tools and the toolbox are still registered, they all have recipes, and show up in JEI.

Steps to reproduce:
- Set `ENABLE_MODULE=false` in both **artisanworktables.module.Tools.cfg** and 
**artisanworktables.module.Toolbox.cfg**
- Launch game
- Open JEI
- They're still here

#### What You Expect to Happen

the tools & the toolbox to be unregistered.

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2836
* CraftTweaker: 1.12-4.1.15
* Artisan Worktables: 1.12.2-1.21.0
* Athenaeum:1.12.2-1.16.0-1-g05e9939

**Comment by codetaylor** [comment]
Same as #151
