### ISSUE TITLE
Lock recipes for Worktables via From The Ground Up

### ISSUE THREAD

**Issue by Xorbah** [codetaylor/artisan-worktables#159]
Title. Is there any way to get this to work in conjunction with the mod From The Ground Up? I posted a similar ticket in their GitHub as well. Basically, the mod locks recipes behind a 'research' gate in which you have to solve a minigame through the use of 'ideas' in order to be able both craft said recipe and see it in JEI. I figured this was worth asking since functionality wise, these tables are similar to vanilla crafting tables and that is what From The Ground Up locks recipes for.

Ticket on their Github can be found at - 

https://github.com/Astavie/From-the-Ground-Up/issues/58

The mod is located on Curseforge via this link - 

https://minecraft.curseforge.com/projects/from-the-ground-up?gameCategorySlug=mc-mods&projectID=250717

**Comment by codetaylor** [comment]
Functionally, AW tables have similarities to vanilla, but under the hood they are completely different.

It is likely that this would require custom work on AW as well as FGU, but I can't say for sure without first studying FGU.

**Comment by Xorbah** [comment]
I really hope this sees some progression. I have been attempting to contact the author of FGU on Discord.

**Comment by codetaylor** [comment]
It will be some time before I can look into this as I have limited time and other commitments and feature requests to consider first.

**Comment by Xorbah** [comment]
Absolutely. Thank you for looking into it at some point regardless.

**Comment by Giskard13** [comment]
As a bit of a workaround you can use the Game Stages integration of FTGU and Worktables to lock recipes behind FTGU research. However, the item still appears in JEI just without the recipe being visible. Not sure if there is a way to hide it, but I'm experimenting.

**Comment by Xorbah** [comment]
Let me know what you come up with.

**Comment by codetaylor** [comment]
Leaving this here for future me:

https://github.com/Astavie/From-the-Ground-Up/tree/1.12/src/main/java/ftgumod/api
https://github.com/codetaylor/artisan-worktables/tree/master/src/api/java/com/codetaylor/mc/artisanworktables/api/recipe/requirement

Try implementing an AW requirement that uses the FTGU api.

**Comment by JadianRadiator** [comment]
@Xorbah your request is already entirely possible, and has been for some months.
All you need to do, is install and use the Game Stages mod.
From The Ground Up research can be set to unlock stages in Game Stages.
And Artisan's Worktables recipes can be locked behind stages in Game Stages.
Tacking on the other Game Stages addons lets you lock certain modded stuff behind the FTGU research too.
With FTGU, Game Stages, and the Tinker Stages addon you could even lock Tinkers Constructs behind FTGU research.

Also, I don't know whether @codetaylor will want to close this now or not.

**Comment by Xorbah** [comment]
I've taken over development of FTGU and am looking into doing this without
the need for workarounds.

**Comment by codetaylor** [comment]
This has been implemented in-dev as a module for Artisan Integrations.

```java
import mods.artisanworktables.builder.RecipeBuilder;
import mods.artisanintegrations.requirement.FTGU;

RecipeBuilder.get("basic")
  .setShapeless([<minecraft:dirt>])
  .addOutput(<minecraft:cobblestone>)
  .addRequirement(FTGU.allOf(["ftgumod:survival/defense"]))
  .create();
```

Allows you to lock recipes behind research using AW's recipe requirement system. Also hides locked recipes in JEI.
