### ISSUE TITLE
[Suggestion] Tools for basic worktable

### ISSUE THREAD

**Issue by Smartaros** [codetaylor/artisan-worktables#16]
I think this is a good idea to add something like wrench/screwdriver/

**Comment by codetaylor** [comment]
I don't have any plans to add tools for the basic table. The basic table is meant to be generic or universal in theme and adding tools for it, like a wrench and screwdriver, would put emphasis on a specific type of use for the table. I'm leaving the basic table's usage open to interpretation by the pack designer. I intend pack makers to use existing tools from other mods, or create their own tools with mods like ContentTweaker.

I may be open to adding a tool for the basic worktable in the future, but it would have to be a very generic, universal type of tool - something along the lines of a multi-tool.

That being said, I do like the idea of adding a wrench and screwdriver. I plan to add an engineering table and I see the wrench and screwdriver as a good fit for that table.

**Comment by codetaylor** [comment]
Coming soon(tm)!

![image](https://user-images.githubusercontent.com/1240716/34795604-b274755e-f607-11e7-9197-db1b5b6168de.png)

**Comment by NoiZeBeAsT** [comment]
Let me say that your mod is definetily underrated! It is so amazing!!

I wanna make some suggestions:
* Make the tables able to accept/require more than one tool.
* A magic related table with tools like wands, lenses or some arcane gadgets. :)
* A cooking related table with appropriate tools.
* A liquid related table, like a cauldron or maybe even a kitchen sink? :)

**Comment by codetaylor** [comment]
An Engineer's Driver and Engineer's Spanner has been added and is available in 1.12.2-1.7.10
