### ISSUE TITLE
Add support for recipes that consume time to complete

### ISSUE THREAD

**Issue by mcmso** [codetaylor/artisan-worktables#161]
It's not an lssues
I'm sorry, but I can't sign in to discord and twitch because of a web problem. I can only express my Suggestions in this way

**Comment by codetaylor** [comment]
Yeah? So, what's the suggestion?

**Comment by mcmso** [comment]
> Yeah? So, what's the suggestion?
Compositing takes some time, and a small countdown GUI can be added to indicate how long it will take to composit the item

**Comment by mcmso** [comment]
> Yeah? So, what's the suggestion?

I don't know if I make myself clear. My English is not very good

**Comment by codetaylor** [comment]
I don't understand what you mean by `Compositing` or how it relates to the mod Artisan Worktables. There isn't anything in the mod that requires time or a countdown.

**Comment by mcmso** [comment]
> I don't understand what you mean by `Compositing` or how it relates to the mod Artisan Worktables. There isn't anything in the mod that requires time or a countdown.

![image](https://user-images.githubusercontent.com/46519955/58523109-d6123980-81f5-11e9-89f9-878551280ef9.png)
Let me give you an example. Maybe if you look at this picture you can see what I mean
I want you to be able to add that kind of functionality

**Comment by codetaylor** [comment]
Again, I don't see how this relates to [Artisan Worktables](https://minecraft.curseforge.com/projects/artisan-worktables). Are you sure you're on the right issue tracker?

**Comment by codetaylor** [comment]
Are you asking for Artisan Worktables to support recipes that take time to complete?

**Comment by mcmso** [comment]
> Again, I don't see how this relates to [Artisan Worktables](https://minecraft.curseforge.com/projects/artisan-worktables). Are you sure you're on the right issue tracker?

I'm not giving feedback,I just hope you can add a customizable feature of "duration" to Artisan Worktables

**Comment by mcmso** [comment]
> support recipes that take time to complete?

That seems to be what I was thinking.Recipes that take time to complete using Artisan Worktables

**Comment by codetaylor** [comment]
Ah, I understand now. It would take a lot of work to implement something like that. I'm not sure if that is something that I will implement, however, I will keep the suggestion in the backlog in case I decide to implement it in the future.

Thank you for the suggestion.

**Comment by mcmso** [comment]
> 啊，我现在明白了。实现类似的东西需要做很多工作。我不确定这是否是我要实施的内容，但是，如果我决定将来实施它，我会在备份中保留建议。
> 
> 感谢您的建议。



> Ah, I understand now. It would take a lot of work to implement something like that. I'm not sure if that is something that I will implement, however, I will keep the suggestion in the backlog in case I decide to implement it in the future.
> 
> Thank you for the suggestion.

Thank you for your patience with my inaccurate English

**Comment by codetaylor** [comment]
Available in the mod Artisan Automation
