### ISSUE TITLE
Gregtech API Issue

### ISSUE THREAD

**Issue by bookerthegeek** [codetaylor/artisan-worktables#163]
# Heyo
Was sorting through my startup log looking for issues and something came up from your mod. Seems their is an issue with your implamentation of the GT:CE Tool Handler, or more specifically with the `gregtech.api.items.IDamagableItem`.

#### What Happens
The following comes up in the Log.

#### What You Expect to Happen
For it not to come up in the Log.

#### Log
Can be found [HERE](https://gist.github.com/bookerthegeek/dc2fb204f3876ab7872ce8022c2ec560)

#### Affected Versions
* Minecraft: 1.12.2
* Forge: 14.23.5.2836
* CraftTweaker: 4.1.18
* Artisan Worktables: 1.21.2
* Athenaeum: 1.16.0
* GregTech Community Edition: 1.8.1.404

**Comment by codetaylor** [comment]
What version of GTCE?

**Comment by bookerthegeek** [comment]
The latest? jk... `gregtech-1.12.2-1.8.1.404.jar	` Also updated first post.

**Comment by codetaylor** [comment]
Thanks!

It looks like on [April 9, 2019](https://github.com/GregTechCE/GregTech/commit/34dc945c2d53db13613083df493757b9f776c5e5#diff-dd88bae060038ad09a6d3489db0074fe) the api class `gregtech.api.items.IDamagableItem` was renamed to `gregtech.api.items.IToolItem`.

I can fix this, but I don't know how long this compatibility feature will hold up given that it looks like the primary GTCE api method Artisan Worktables uses to damage GTCE items [may be scheduled for removal](https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/util/GTUtility.java#L273). If this method is removed in the future, as the comment implies, more time will be needed to fix.

I have inquired here: https://github.com/GregTechCE/GregTech/issues/851
