### ISSUE TITLE
Crafting Slot Locking Feature (Ghost Items)

### ISSUE THREAD

**Issue by Damien-Reave** [codetaylor/artisan-worktables#166]
Hi there. I'm the dev being the modpack Omnifactory and I've been looking into including Artisan Worktables in the upcoming expert mode version of the pack. I really enjoy the interface, the tools with various durability, ease of creating recipes, and more. I do have two feature requests, however.

The first is a config option to customize the background color of the background. The foreground element of the tables is thematic and gorgeous, one of my favorite parts of the mod, but the background can at times make certain items difficult to see. Specifically I'm talking about the color of the area outlined in red, in between the grid lines.

https://imgur.com/a/hLKZIdd

Being able to customize the color of the output slot would also be nice, but is less important.

Secondly, I'd like to request a method to lock in a recipe (with ghost images of the ingredients remaining after they're consumed), and also supporting items being inserted via hopper / item conduit into the table going into these slots, round-robin style, as a priority over the slots in the bottom.

If round robin-ing the items in isn't an option, then a button that auto allocates items from the bottom slots evenly into the locked slots of the recipe would be just about as good.

Thank you for your time!

**Comment by VariableVixen** [comment]
I believe automation is already _planned_ but not yet _implemented_. The closest I think we have so far is using the designer's table to make a blueprint, and then using _other_ mods to take that blueprint and various items and assemble the thing in question automatically.

**Comment by codetaylor** [comment]
Thank you for your suggestions. Your feedback is important.

In the future, please follow the feature request guidelines found in this project's [README.md](https://github.com/codetaylor/pyrotech):

> * Restrict to one request, idea, or suggestion per issue; if you have multiple ideas, create multiple issues. When ideas are separated into individual issues, it is much easier to organize, tag, discuss, and close those individual issues than it is a list of ideas in one issue. Additionally, it is easier for others to check if their idea has already been suggested before posting.

**Comment by codetaylor** [comment]
Regarding modification of the slot background colors, I could draw some colored quads in the slot backgrounds and expose the colors with a config. I'm thinking just one color for each type of table, so for example, all three farmer tables would have one color config option that would govern the color of all the table's input slots. What do you think?

The idea you proposed for the... I'll call it semi-automation has been bouncing around in my head for a week and I think I really like it. I have ideas for full automation, but this is something that I might build into the base mod in the future.

The gif below is the last mockup I did while thinking about the full automation. I don't know yet how the mockup will pan out, but I really like the idea you proposed.

![aw-auto](https://user-images.githubusercontent.com/1240716/60402640-2c510000-9b47-11e9-8086-7f1ce3e85236.gif)

**Comment by Damien-Reave** [comment]
Yes, one color per worktable is fine, anything more is just customization overkill imo.

The mockup looks amazing! Is that power in the table I see? Very very cool!

**Comment by codetaylor** [comment]
That is indeed power!

The idea so far is this...

This would basically be a two block setup: one block would supply the power and the other would consume the power to advance the blue work meter. When the work meter is full, the recipe is complete.

The base AW mod would get the crafting block and a power block that runs on the Forge energy capability. In the future I am going to extract most of the AW compat into a second AW Compat mod. That mod could then provide other power blocks that would accept other mods' power, like BWM mechanical power or Botania mana power.

**Comment by codetaylor** [comment]
I've split the custom color request into a separate issue: #174

**Comment by codetaylor** [comment]
@Damien-Reave the custom color feature has been implemented in-dev, see #174 for more info.
