### ISSUE TITLE
More tool slots and tables

### ISSUE THREAD

**Issue by NoiZeBeAsT** [codetaylor/artisan-worktables#17]
First, let me say that your mod is so genius!
It is definetily underrated!

I wanna make some suggestions:
* Make the tables able to accept/require more than one tool. (So you could add crafting recipes requiring tool x AND tool y)
* A magic related table with tools like wands, lenses or some fancy arcane gadgets. :)
* A cooking related table with appropriate tools.
* A liquid related table, like a cauldron or maybe even a kitchen sink? :)

**Comment by codetaylor** [comment]
> Make the tables able to accept/require more than one tool. (So you could add crafting recipes requiring tool x AND tool y)

Definitely a possibility.

> A magic related table with tools like wands, lenses or some fancy arcane gadgets.

A magical table is in the works, see: https://github.com/codetaylor/artisan-worktables/issues/11

> A cooking related table with appropriate tools.

Not a bad idea...

> A liquid related table, like a cauldron or maybe even a kitchen sink?

I'll have to think about how to implement this one, but definitely a possibility.

Thanks for the suggestions! I'm glad you're enjoying the mod. :)

**Comment by codetaylor** [comment]
Coming soon(tm)!

![2018-01-11_17 37 04](https://user-images.githubusercontent.com/1240716/34855841-c49064b0-f6f6-11e7-83b9-457c0487fd71.png)

**Comment by codetaylor** [comment]
The Mage's Worktable is available in version 1.12.2-1.7.10

**Comment by NoiZeBeAsT** [comment]
Awesome! Keep up the amazing work!! :)

**Comment by codetaylor** [comment]
I'm going to go ahead and close this issue. The tier two tables in the next beta release will support up to two tools. Also, I have made a note of the cooking table idea and probably won't introduce a fluid-only table.

Thank you for the inspiration. :)
