### ISSUE TITLE
Recipe Not Working?

### ISSUE THREAD

**Issue by vizthex123** [codetaylor/artisan-worktables#170]
#### Issue Description:

Recipes won't get added

#### What Happens

It gives me this error when I do /ct syntax: 
![ArtTableBreak](https://user-images.githubusercontent.com/31721920/61092060-4c67a580-a40a-11e9-8445-1672d021a5b4.png)

#### What You Expect to Happen

The recipes to be added

#### Script
https://pastebin.com/GjziivPW

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* CraftTweaker: 4.1.19
* Artisan Worktables: 1.21.5
* Athenaeum: 1.17.2

**Comment by codetaylor** [comment]
Two things:
1. The second `RecipeBuilder.get("mage")` in your script is never assigned to the `builder` variable
2. The second `RecipeBuilder.get("mage")` is missing a `;` at the end.

For help with CraftTweaker scripts, you can join [discord.blamejared.com](discord.blamejared.com)
For help with Artisan Worktables, you can join [discord.codetaylor.com](discord.codetaylor.com)

**Comment by vizthex123** [comment]
Ah ok, thanks! Can't believe I didn't notice the missing semicolon.

**Comment by codetaylor** [comment]
You're welcome :)
