### ISSUE TITLE
CraftingTweaks Compatibility

### ISSUE THREAD

**Issue by Boolyman** [codetaylor/artisan-worktables#171]
CraftingTweaks allows a full stack of items to be crafted by right clicking the output.  Can you add this functionality to your tables, or allow compatibility with the CraftingTweaks function?

**Comment by codetaylor** [comment]
Similar to #80

**Comment by codetaylor** [comment]
Thank you for the suggestion, however I won't be implementing this.

This mod has already grown far beyond its original scope and I would like to spend my limited time working on other projects.
