### ISSUE TITLE
Updating screen events  java.lang.NullPointerException

### ISSUE THREAD

**Issue by xxlio109** [codetaylor/artisan-worktables#172]
crash log https://gist.github.com/xxlio109/7c925d944a2031eab9b36f4faa80062c

Put into microblockcbe:saw_diamond client crash

FTB Interactions Modpacks

**Comment by xxlio109** [comment]
Replaced with artisanworktables-1.12.2-1.20.2 no problem

**Comment by codetaylor** [comment]
I'm pretty sure I know what the problem is, but I have no way to test it. If I linked a test build, can you test it?

**Comment by codetaylor** [comment]
You're welcome to join discord.codetaylor.com - it would be easy to share a test build there.
