### ISSUE TITLE
[Suggestion] Add recipe copying tool/button visible to creative players

### ISSUE THREAD

**Issue by krisjenner** [codetaylor/artisan-worktables#175]
A tool that could right click on an Artisan Worktable with a recipe inside (and fluid too?) to turn it in to ZS format for use with CraftTweaker.

AND/OR

A button inside Artisan Worktables, visible only to opped/creative players that exports to a text file in main directory/copies the contents to clipboard as above

**Comment by PrincessRTFM** [comment]
What about table tiers? If the recipe is in a lower-tier table, does it limit to only that tier or does it allow higher? If it's in a higher-tier table but would _work_ in a lower tier, does it limit to only this tier and above? Does it not do limits and expect you to do that yourself? How will it handle tools - ore dicting by type, no ore dicting, something else?

**Comment by codetaylor** [comment]
I'm thinking a button, click for shaped, shift + click for shapeless.

It would output the bare minimum, you have to add tools manually.

A dummy output would be included for easy replacement

```java
RecipeBuilder.get("basic")
  .setShaped([
    [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>],
    [<minecraft:cobblestone>, null, <minecraft:cobblestone>],
    [<minecraft:cobblestone>, <minecraft:cobblestone>, <minecraft:cobblestone>]])
  .addOutput(<minecraft:air>)
  .create();
```

If the table has a fluid, it would include the fluid. You have to set the amount manually.

```java
.setFluid(<liquid:water> * 1000)
```

If the table has secondary ingredients, it would include them as well.

```java
.setSecondaryIngredients([<minecraft:gravel> * 8, <minecraft:string>])
```

It would give you a template and knock out a bunch of the tediousness.

**Comment by Boolyman** [comment]
This would have saved me so much time.  I have Extended Crafting installed just while I develop the pack just to use their tool, and then edit the info to fit your table.
