### ISSUE TITLE
Crash right click

### ISSUE THREAD

**Issue by Danymaddox** [codetaylor/artisan-worktables#177]
#### Issue Description

*Crash with Right click*

Crash when richgt click the frame of any table with an item causes a crash and the item dissapears.

#### What Happens

Crash when right click the frame table with any item, and the item dissapears.
* Take any artisan's table. Take any item. Open the table and right click with the item anywhere except when the items go.

#### What You Expect to Happen

Not to crash.

#### Script

I've tested this in a new profile and new world, so no script here.

#### Crash Log

Crash Log: https://pastebin.com/W9KyKAP7

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.28.83
* CraftTweaker: Don't need to use any, but I've also tried with CraftTweaker2-1.12-4.1.19 (and it crash)
* Artisan Worktables: artisanworktables-1.12.2-1.21.6
* Athenaeum:athenaeum-1.12.2-1.17.3

**Comment by codetaylor** [comment]
Fixed in `1.12.2-1.21.7`
