### ISSUE TITLE
[Suggestion] Fluid GUI Clarity

### ISSUE THREAD

**Issue by Boolyman** [codetaylor/artisan-worktables#179]
After watching a few streamers play test my upcoming pack I have noticed one common problem, the fluid tank in the GUI can be misleading at times. The problem occurs usually when I increase the fluid capacity of a table.  When the capacity is increased the fluid  requirement for the recipe becomes such a small sliver that the player doesn't even notice it's there. They end up scratching their head as the recipe fails and then going back into JEI until they finally realize they should hover over the fluid tank GUI to discover that there was a tiny requirement of fluid. The second issue stems from if a fluid is the same color as the background of the GUI. for instance creosote fluid used in the carpenter table hardly shows up against the brown GUI.

I know this is a small quality-of-life suggestion but if you were to add a minimum size for the fluid representation in the GUI tank so that it always shows at least a noticeable amount if the recipe requires fluid.  For example if a recipe calls for 1000mb, it shows the correct amount in the GUI but if the recipe calls for 50mb of fluid (which wouldn't normally be visible) the GUI will scale the render so that it's at least visible. And/or making the fluid tank portion of the GUI for each table have a white background so that most fluid colors will show up very clearly.

**Comment by codetaylor** [comment]
I agree about the minimum fluid display in JEI.
Are you also talking about a minimum fluid display in the table gui?

Regarding the background colors: a color feature was suggested as a solution to potential visibility and possibly accessibility issues and the feature has been implemented in-dev for the next release `1.22.0`. Results of the feature can be seen here https://github.com/codetaylor/artisan-worktables/issues/174#issuecomment-515716160

**Comment by Boolyman** [comment]
Not in the physical table, just in the JEI recipe view, since thats where everyone references to prepare a recipe.  If you cant do one without the other I still think its a worthwhile improvement.

**Comment by Boolyman** [comment]
The color option changes look great

**Comment by codetaylor** [comment]
@Boolyman I'm thinking about just making the JEI fluid display always 50% or 75% regardless of the actual input amount. When a player is looking up a recipe, I think it is more important to have the fluid visible than it is for the player to have an idea of how much fluid is required in relation to the tank capacity. I think a player would almost always hover over the fluid to determine exactly what kind of fluid and the quantity required.

What are your thoughts on this?
