### ISSUE TITLE
Recipes not working

### ISSUE THREAD

**Issue by JWTHDYTWA** [codetaylor/artisan-worktables#181]
I created script. It successfully loaded. It's showing in JEI:
![2019-08-19_23 20 09](https://user-images.githubusercontent.com/30724185/63281930-f246e380-c2d7-11e9-89f6-c03f2e8dcbf9.png)
But the real workbench doesn't allow me to craft actual item:
![2019-08-19_23 22 04](https://user-images.githubusercontent.com/30724185/63282033-2cb08080-c2d8-11e9-8468-1edf53569286.png)
P.S. Don't pay attention to emeralds counted as 8 in recipe - it's visual bug. I can't do any craft with Artisan Worktables.
[Here's script](https://gist.github.com/Warrock3280/2d9b9e8f6bf609abde3d4b72f5d37ca1)
It's possible mod interaction bug.
Mod Verion: 1.21.7

**Comment by codetaylor** [comment]
Do any of the other recipes in your script work, or is it just the recipe shown that doesn't work?

Can you explain why emeralds are shown with a quantity of 8?

Also... please follow the issue template. It is provided for a reason.

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft:
* Forge:
* CraftTweaker:
* Artisan Worktables:
* Athenaeum:

**Comment by codetaylor** [comment]
I can't reproduce this. 

What is the durability of the green tools you're using?

Here's what I've tried:

### Script
```java
import mods.artisanworktables.builder.RecipeBuilder;
RecipeBuilder.get("jeweler")
  .setShaped([
      [<ore:gemEmerald>, <botania:manaresource>, null],
      [<botania:manaresource>, null, <botania:manaresource>],
      [null, <botania:manaresource>, null]])
  .setSecondaryIngredients([<botania:manatablet>])
  .addTool(<ore:artisansGemCutter>, 64)
  .addTool(<ore:artisansPliers>, 64)
  .setFluid(<liquid:lava> * 1000)
  .addOutput(<botania:manaring>)
  .create();
```

### Result
![image](https://user-images.githubusercontent.com/1240716/63288294-2dfa9280-c271-11e9-8a90-75c17c793720.png)

### Versions
```
Mods list:
minecraft - Minecraft - 1.12.2
mcp - Minecraft Coder Pack - 9.42
FML - Forge Mod Loader - 8.0.99.99
forge - Minecraft Forge - 14.23.5.2838
artisanintegrations - Artisan Integrations - @@VERSION@@
jei - Just Enough Items - 4.14.4.264
baubles - Baubles - 1.5.2
botania - Botania - r1.10-361
ftgumod - From the Ground Up - 1.12.2-b1.3.16
crafttweaker - CraftTweaker2 - 4.1.19
codechickenlib - CodeChicken Lib - 3.2.2.353
gregtech - GregTech Community Edition - 1.8.1.404
artisanworktables - Artisan Worktables - @@VERSION@@
athenaeum - Athenaeum - @@VERSION@@
reskillable - Reskillable - 1.12.2-GRADLE:BUILD
ctgui - CT-GUI - 1.0.0
bookshelf - Bookshelf - 2.3.566
gamestages - Game Stages - 2.0.108
```

**Comment by JWTHDYTWA** [comment]
> Do any of the other recipes in your script work, or is it just the recipe shown that doesn't work?

As i said, none of recipes works. I've tried all the recipes of my script.

> Can you explain why emeralds are shown with a quantity of 8?

It's common JEI visual bug. I used to see it in many modpacks, for example Coal Blocks in Resonator recipe of ExtraUtils.

> What is the durability of the green tools you're using?

It's full Terrasteel tools with durability over 1500.

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* CraftTweaker: 4.1.19
* Artisan Worktables: 1.21.7
* Athenaeum: 1.17.3

**Comment by JWTHDYTWA** [comment]
Here's some mods that could possibly cause the problem:
Inventory Tweaks
Crafting Tweaks
NoMoreRecipeConflict (Recipe Handler)
Iblis
JustEnoughIDs
Quark
Random Tweaks
Pickle Tweaks
Real Bench
FastWorkbench
FoamFix
VanillaFix

**Comment by codetaylor** [comment]
Can you try disabling some mods to see if the problem goes away? It would help to narrow down which mod is affecting the tables.

**Comment by BlahBlah81** [comment]
It's common JEI visual bug. I used to see it in many modpacks, for example Coal Blocks in Resonator recipe of ExtraUtils. What was the fix for that issue. as it seams it affects the runic alter from botania making it impossible to craft earth runes.
Here is what i could narrow it down to as i have these similar mods in my own pack.
FoamFix
VanillaFix
Inventory Tweaks
Crafting Tweaks
