### ISSUE TITLE
Carpenter Table Ignores WithTag Data

### ISSUE THREAD

**Issue by WittyWhiscash** [codetaylor/artisan-worktables#182]
#### Issue Description

Carpenter Table seems to ignore the .withTag data.

#### What Happens

In order to reproduce the issue:
1. Use affected minecraft and mod versions.
2. Structure your scripts folder as such:
```
scripts
    expert
        StorageDrawers.zs
    reference
        Reference.zs
```
3. Open Minecraft and check the recipe for Spruce Drawer 1x1. It should show the recipe for the Oak Drawer 1x1.
4. Change all instances of "carpenter" to "basic".
5. Open Minecraft and check the recipe for Spruce Drawer 1x1. It should now show the recipe for the Spruce Drawer.

What happens:
When Carpenter is used, all references to recipes refer to the proper block, but not with the proper tag data.
When the Basic one is used, all references to recipes refer to their proper references.

#### What You Expect to Happen

When the Carpenter is used, all references to recipes should refer to their proper references with the proper tag data.

#### Script

scripts/reference/Reference.zs
https://pastebin.com/GAF7TrnN
scripts/expert/StorageDrawers.zs
https://pastebin.com/jp84X8dQ

#### Crash Log

No crashes, but crafttweaker.log:
https://pastebin.com/FyjWqrNC

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* CraftTweaker: 1.12-4.1.19
* Artisan Worktables: 1.12-1.21.7
* Athenaeum: 1.12.2-1.17.3
* Storage Drawers: 1.12.2-5.3.8

**Comment by codetaylor** [comment]
So I dug into this and I'm not finding any unexpected behavior.

I tested with the simplified test script below. Hovering either of the output items below and pressing `R` resulted in JEI displaying all recipes that output that item, regardless of NBT. This is standard JEI behavior which can be demonstrated by hovering a `<storagedrawers:basicdrawers:2>.withTag({material: "acacia"})` and pressing `R` - *ALL* storage drawer recipes are shown, regardless of NBT.

```java
import mods.artisanworktables.builder.RecipeBuilder;

// Carpenter Worktable
// Hover "Dirte" and press R, JEI displays both recipes.
// Hover "Undirte" and press R, JEI displays both recipes.
// Both recipes work correctly in the table.

// Change to "basic"

// Basic Worktable
// Hover "Dirte" and press R, JEI displays both recipes.
// Hover "Undirte" and press R, JEI displays both recipes.
// Both recipes work correctly in the table.

RecipeBuilder.get("carpenter")
    .setName("name1")
    .setShaped([
        [<minecraft:diamond>]
    ])
    .addOutput(<minecraft:dirt>.withTag({RepairCost: 0, display: {Name: "Dirte"}}))
    .create();

RecipeBuilder.get("carpenter")
    .setName("name2")
    .setShaped([
        [<minecraft:string>]
    ])
    .addOutput(<minecraft:dirt>.withTag({RepairCost: 0, display: {Name: "Undirte"}}))
    .create();
```

**Comment by WittyWhiscash** [comment]
Odd, the GUI must have had a small bug that just required a restart or five, because it's working as intended now. It's honestly strange how code works these days. I'm not entirely sure what went on, but if it's working now, I guess we call this closed.

**Comment by codetaylor** [comment]
Sounds good. Thanks for the report regardless!
