### ISSUE TITLE
[suggestion] Worktable Type

### ISSUE THREAD

**Issue by ISurrealI** [codetaylor/artisan-worktables#183]
What if there was a thing that makes recipes cant make on other types of worktable. Example:
`.setWorktableType("workshop")`

will make it just can get made on **workshop** type of the worktable.

`.setWorktableType("worktable", "workstation"`

That recipe can just made on **worktable** or **workstation** and cannot get crafted on **workshop**. 

I really don't know how to say this so i gived examples.

**Comment by codetaylor** [comment]
Recipes can be restricted by minimum tier and maximum tier of table.

See: https://artisan-worktables.readthedocs.io/en/latest/recipes/tiers/
