### ISSUE TITLE
Worktable crash

### ISSUE THREAD

**Issue by Mrthomas20121** [codetaylor/artisan-worktables#185]
#### Issue Description

Artisan worktable crash with the new creative feature.

#### What Happens

i set the artisan worktable to creativez
i put a item on a artisan worktables
i changed the artisan worktable mode to survival
i placed the item at the same place the item was placed in creative worktable
the game crashed

#### What You Expect to Happen

i expected the worktable to put my item in the worktable.

#### Script
no scripts caused this issue.

#### Crash Log

https://paste.dimdev.org/ixohiyakas.mccrash

#### Affected Versions

* Minecraft: 1.12
* Forge: 14.23.5.2838
* CraftTweaker: 4.1.19
* Artisan Worktables:1.22.0
* Athenaeum: 1.17.4

**Comment by codetaylor** [comment]
Not solved.

New trace: https://paste.dimdev.org/ikolesanag.coffeescript

**Comment by codetaylor** [comment]
I'm assuming since I didn't hear from you that you haven't had the crash again?

I'm going to go ahead and close this.
