### ISSUE TITLE
Creative mode and lock buttons don't show up

### ISSUE THREAD

**Issue by SureenInk** [codetaylor/artisan-worktables#186]
#### Issue Description

The buttons for the creative mode things and the lock button don't have a visible appearance on the tables, but are still clickable and the tooltip pops up.

https://imgur.com/a/RkZgunL Image to show what I mean

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* CraftTweaker: 1.12-4..1.19
* Artisan Worktables: 1.12.2-1.22.1
* Athenaeum: 1.12.2-1.17.4

**Comment by codetaylor** [comment]
This was solved in Discord.

OP was using a modified texture that didn't have the new button textures in it.
