### ISSUE TITLE
Shift clicking patterns into scribes table crashes the game. Placing any item into this slot deletes it.

### ISSUE THREAD

**Issue by UnlimatedStone9** [codetaylor/artisan-worktables#190]
#### What Happens

Shift clicking patterns into the scribes table immediately crashes the game.
Placing any item into the slot manually deletes the item.

#### What You Expect to Happen

The item to go into the slot perfectly fine.

* Describe what you expect to happen

#### Crash Log

https://paste.dimdev.org/pifiwawogo.mccrash

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* Artisan Worktables: 1.12.2-1.22.3
* Athenaeum: 1.12.2-1.17.4

**Comment by codetaylor** [comment]
I've reproduced the shift click crash. Shift clicking an empty pattern into the pattern slot of any table that has a valid vanilla recipe in the crafting grid will produce an exception.

> Placing any item into the slot manually deletes the item.

I am unable to reproduce the item deletion. @UnlimatedStone9 can you please provide exact steps to reproduce the item deletion? What slot? What circumstances? Thanks :)

**Comment by codetaylor** [comment]
The crash has been sorted out, but I still cannot reproduce the item deletion.

![image](https://user-images.githubusercontent.com/1240716/65449337-9c41f000-ddef-11e9-8620-db8220e6a4f7.png)

It looks like if you click just outside of the item slots in the pattern window, the items in the cursor will be dropped in the world. That's the closest I could get to item deletion.

**Comment by UnlimatedStone9** [comment]
I'm not certain then what causes it, clicking onto the circled part here (the paper and the arrow) seems to delete the item, elsewhere will drop it into the world.
![image](https://user-images.githubusercontent.com/40124890/65459307-852eec80-de47-11e9-8d89-676481b21a25.png)

**Comment by codetaylor** [comment]
> [...] seems to delete the item [...]

What is the item?

**Comment by codetaylor** [comment]
Item deletion was being caused by JEI's bookmark pane overlapping the pattern box.
