### ISSUE TITLE
Thaumcraft Essentia Integration

### ISSUE THREAD

**Issue by Danymaddox** [codetaylor/artisan-worktables#191]
It would be great if Artisan's Worktables had Thaumcraft essentia compatibility, maybe using some Transfuser.

Thank you!

**Comment by Lord-Felidae** [comment]
Maybe it could be table that has the six crystal slots and uses Vis from the Aura instead of a liquid, on top of the extra slots?

**Comment by codetaylor** [comment]
Thank you for the suggestion, however I won't be implementing this.

This mod has already grown far beyond its original scope and I would like to spend my limited time working on other projects.
