### ISSUE TITLE
Artisan tables deleting items

### ISSUE THREAD

**Issue by Boolyman** [codetaylor/artisan-worktables#194]
#### Issue Description

Artisan tables are deleting items that have been accidentally placed in the outy put.

#### What Happens

Start with empty table
Deposit any item into the output
Place any item into the crafting grid
Output item is deleted
You do not need a successful crafting

#### What You Expect to Happen

Items to not be deleted...and items not to be able to go back into output.

#### Affected Versions

* Minecraft: 1.12.2
* Forge: forge-14.23.5.2847
* CraftTweaker: 1.12.2-4.9.1
* Artisan Worktables: 1.12.2-1.22.5
* Athenaeum: 1.12.2-1.17.4

**Comment by zepanv** [comment]
This just happened to me as well playing the Seablock: Rustic Waters pack.  It ate my needle thing that I got from a quest reward and can't progress.
