### ISSUE TITLE
Output of recipes affected by right-clicking

### ISSUE THREAD

**Issue by Andr0oS** [codetaylor/artisan-worktables#198]
#### Issue Description

Crafting recipes that have multiple output items with right click returns one fewer than the recipe crafts for normally.

#### What Happens

When using right-click to craft a recipe that has multiple items output (i.e. one log into four planks), the output of the recipe is one item fewer than the expected result (i.e. one log into three planks).

#### What You Expect to Happen

Recipes return the correct amount of the output item.

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CraftTweaker: CraftTweaker2 - 1.12-4.1.19
* Artisan Worktables: 1.12.2-1.22.5-2-g36dbae6
* Athenaeum: 1.12.2-1.17.4
* Modpack version:  Rustic Waters 10.6

**Comment by Kuzym** [comment]
I had a similar issue happen to me while playing DDSS version 6.2. I right-clicked the output of Fluiducts (and later again with Fluxducts) and both times received half a stack with the other half disappearing.

DDSS 6.2
artisanworktables-1.12.2-1.22.5.jar
