### ISSUE TITLE
Possibility of requiring vis from TC for Mage's worktables

### ISSUE THREAD

**Issue by jonthemoron** [codetaylor/artisan-worktables#203]
Title, I think it would allow more possibilities for custom recipes if Artisan Worktables/Integrations had a compatibility feature with Thaumcraft that would allow you to write recipes requiring vis in a chunk similar to how the arcane worktable in Thaumcraft requires a certain amount of vis to be in the chunk. I realize this could be very in depth or a lot to ask for, simply a suggestion that I think would be cool to include somewhere down the line if possible.

**Comment by codetaylor** [comment]
Thank you for the suggestion, however I won't be implementing this.

This mod has already grown far beyond its original scope and I would like to spend my limited time working on other projects.
