### ISSUE TITLE
Possibility of using gases in recipes

### ISSUE THREAD

**Issue by Omegapsychosis** [codetaylor/artisan-worktables#204]
I was thinking it would be interesting to be able to require Gases from mods such as Mekanism as a requirement in recipes. Perhaps as an additional feature in Artisan integrations?

**Comment by codetaylor** [comment]
I'm not too familiar with Mekanism, so correct me if I'm wrong, but aren't gasses just fluids?

**Comment by VariableVixen** [comment]
I think Mekanism treats them specially so you can't use fluid transport mechanics, you need to use their gas pipes specifically

**Comment by codetaylor** [comment]
Thank you for the suggestion, however I won't be implementing this.

This mod has already grown far beyond its original scope and I would like to spend my limited time working on other projects.
