### ISSUE TITLE
Botania Incompatibility?

### ISSUE THREAD

**Issue by Rongmario** [codetaylor/artisan-worktables#206]
* Minecraft: 1.12.2
* Forge: -2847
* Artisan Worktables: 1.22.11
* Artisan Integration: 1.1.1
* Athenaeum: 1.17.4
* Botania: 362

https://paste.dimdev.org/icisowefig.mccrash

**Comment by codetaylor** [comment]
Should be fixed in Artisan Integrations 1.1.2
