### ISSUE TITLE
Support for Nuclearcraft Materials

### ISSUE THREAD

**Issue by DarkYuan** [codetaylor/artisan-worktables#208]
Nuclearcraft adds a lot of different materials, and there are some that would be very well-suited for tools. Boron, Ferroboron, Tough Alloy, and Hard Carbon make the most sense. For reference, Tinker's Construct has parts for those, plus Boron Nitride, Thorium, Uranium, Magnesium, and uh, Chocolate.

**Comment by codetaylor** [comment]
Do you have time to post those materials as json like you did for #207 ?

**Comment by DarkYuan** [comment]
Aha! Got them all figured out, thanks to [(source)](https://github.com/turbodiesel4598/NuclearCraft/blob/1a03293c2545480f1d9182de7f703478c5b4b56b/src/main/java/nc/integration/tconstruct/TConstructMaterials.java#L23-L26). Turns out ferroboron isn't actually a registered tinker's material, but boron nitride is, so I made that instead. For the oredict key, not sure if you want to go with `artisansToolToughAlloy` for specification or just `artisansToolTough` based on precedent.

```
{
    "name": "boron",
    "harvestLevel": 2,
    "maxUses": 550,
    "efficiency": 8.0,
    "damage": 2.5,
    "enchantability": 6,
    "color": "7D7D7D",
    "shiny": true,
    "ingredient": "ore:ingotBoron",
    "langKey": "material.athenaeum.boron",
    "oreDictKey": "artisansToolBoron"
},
{
    "name": "toughalloy",
    "harvestLevel": 3,
    "maxUses": 950,
    "efficiency": 10.0,
    "damage": 3.0,
    "enchantability": 15,
    "color": "150F21",
    "shiny": false,
    "ingredient": "ore:ingotTough",
    "langKey": "material.athenaeum.toughalloy",
    "oreDictKey": "artisansToolToughAlloy"
},
{
    "name": "hardcarbon",
    "harvestLevel": 3,
    "maxUses": 1250,
    "efficiency": 11.0,
    "damage": 3.0,
    "enchantability": 12,
    "color": "195970",
    "shiny": false,
    "ingredient": "ore:ingotHardCarbon",
    "langKey": "material.athenaeum.hardcarbon",
    "oreDictKey": "artisansToolHardCarbon"
},
{
    "name": "boronnitride",
    "harvestLevel": 4,
    "maxUses": 1950,
    "efficiency": 12,
    "damage": 3.5,
    "enchantability": 20,
    "color": "75B269",
    "shiny": true,
    "ingredient": "ore:gemBoronNitride",
    "langKey": "material.athenaeum.boronnitride",
    "oreDictKey": "artisansToolBoronNitride"
}
```

**Comment by codetaylor** [comment]
Thank you very much! This will save me a considerable amount of time. :)

**Comment by DarkYuan** [comment]
No problem! I hope this gets included in the next update of DD&SS
