### ISSUE TITLE
[Suggestions] Other types of 'tables'

### ISSUE THREAD

**Issue by ghost** [codetaylor/artisan-worktables#21]
First of all: I love this mod. It makes pack development and progression so much more flexible and diverse. I like the idea having mods that only provide 'machines' and then add their functionality yourself.
Secondly: The following ideas/suggestions may or may not fit this mod and would perhaps fit better in their own mod; you decide (and you may obviously feel free to reject anything!) :-) 
Some of these ideas come from TFC, they would all need to be 'programmable' with crafttweaker.

Grindingstone (tool sharpening)
Not many people know that bronze tools and iron tools are more or less equal in hardness and durability (in RL). The reason people switched in ancient times was because iron tools could be sharpened (repaired) while bronze could not.
Right-clicking a tool on a grindstone would repair them. Each tool takes specific time to repair as well as can only be repaired maximum amount of times.

Spinningwheel & Loom
Taking raw material (wool, flax, cotton, etc (provided by other mods?) in a spinning wheel, turns them into yarn/string.
Then placing this string in a loom turns it into fabric (cotton, linnen, jute, wool, etc.)

Barrels (wood)
- Age fluids (transform them over time)
- Mix fluids
- Change fluids by adding items (over time)
- Change items by soaking them (over time)

Drying rack
Dry items over time
Perhaps have 2 types: vertical and horizontal

Cauldron / Cookingpot
Both in metal and clay
Can be placed over (open) fire.
Has input and output grid (multiple inputs/outputs)
Used for cooking stuff in fluids (think soup, stew, etc.)
Needs ladle tool

Different 'Furnaces'
- Furnace
- Bloomery
- Campfire
Each functions on different max temperature. GUI has input and output grid (multiple inputs/outputs) and a fuel slot.
Needs tongs tool

Again, just my ideas/wishes. Do as you wish with them.

**Comment by codetaylor** [comment]
Thank you for taking the time to share this huge list of awesome ideas! These are great. :)

I do believe that they are mostly outside the scope of this mod, but would be a great start for a new mod. I have copied this list into my notes for future reference and will be closing this issue in an attempt to keep the issue tracker clean and relevant.

Thanks again!

**Comment by ghost** [comment]
You're welcome, and thank you :)
