### ISSUE TITLE
Fluid provider

### ISSUE THREAD

**Issue by ghost** [codetaylor/artisan-worktables#211]
As I'm sure you're aware, Seablock makes heavy use of this mod. The problem is that different recipes on the same table may require different fluids. Pipetting them in and out is cumbersome. And having multiple tables messes up the tabs and toolbox. I'd like suggest a tank interface or better yet a fluid provider block. Maybe a vertical half slab that sits on top of the individual tables and can provide up to four fluids. They could be themed with buckets, beakers, etc.
Just an idea. Thanks.

**Comment by codetaylor** [comment]
Thank you for the suggestion, however I won't be implementing this.

This mod has already grown far beyond its original scope and I would like to spend my limited time working on other projects.
