### ISSUE TITLE
[Suggestion] Allow hopper to take the output from the table

### ISSUE THREAD

**Issue by MorphTheMoth** [codetaylor/artisan-worktables#214]
since SeaBlock uses this mod as a core mod and sometimes you need a lot of resources that have to be crafted in the work table, it would be really useful to have a way to automatize those crafting.

**Comment by codetaylor** [comment]
I will not be adding this feature, however, I am working on an automation solution. You're welcome to join the Discord, http://discord.codetaylor.com, if you want to stay updated on the automation feature.
