### ISSUE TITLE
AW creative tab has no icon if worktables are disabled

### ISSUE THREAD

**Issue by SureenInk** [codetaylor/artisan-worktables#215]
When you disabled the worktables (referring to the base level tables not all of them in general), the icon for AW's creative tab is blank.

I kind of expected it might grab the next tier table, like the workstations or workshops if the stations are also disabled. If all three are disabled (maybe someone just wants to utilize the tools? There's a lot, and they are handy even in basic crafting), maybe it could utilize a random tool? Or maybe a unique item can be registered specifically for the icon?

* Minecraft: 1.12.2
* Forge: 14.23.5.2838
* CraftTweaker: 4.1.20
* Artisan Worktables: 1.22.15
* Athenaeum: 1.17.4

**Comment by codetaylor** [comment]
This has been fixed in `1.23.0` by using an unobtainable dummy block with the existing assets for the Basic Worktable.
