### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by Nitess** [codetaylor/artisan-worktables#217]
Just want to apologize for my English. I got a very interesting idea. How about making Tiers for tools? and integrate it into recipes.
Maybe this way of creation is already there, I have not found.
For example, in the modpack there are 4 types of materials for tools. Silicon, iron, diamond. Further, somewhere in json, allocate a place for Tiers materials, silicon 1 Tiers, iron 2 , diamond 3 and steel 4. And in recipes to be able to set the minimum Tiers to create.

for example

```
import mods.artisanworktables.builder.RecipeBuilder;

RecipeBuilder.get("basic")
  .setShapeless([<minecraft:dirt>])
  .addOutput(<minecraft:cobblestone>)
  .addTool(<ore:artisansHammer>, 10)
  .addToolMinTier(3)    (That is, the recipe can be made using a diamond type tool and above)
  .create();
```

It would also be great to have tools with an energy buffer.
And for

`"maxUses": 200,`

is there an infinity parameter?

**Comment by codetaylor** [comment]
Thank you for the suggestion, however it will not be implemented.

This mod has already grown far beyond its original scope and I would like to spend my limited time working on other projects.
