### ISSUE TITLE
Tinkers Parts Compatibility

### ISSUE THREAD

**Issue by Ceifeire** [codetaylor/artisan-worktables#218]
I have looked for this and have not found anything and all my tests have failed. Is it possible to add compatibility to use tinkers parts on the tables, or is there already and way, if so how to format the recipe to use a specific tinkers part?

My current methods had yielded only, use any material of that tinkers part or refusing to accept that specific part.

My example is I am using the tinkers tool rod and it is called out as <tconstruct:tool_rod>, this enables me to use any tool rod for that recipe.

I tried using a random specific part and formatted it like this <tconstruct:kama_head:0:flint>, this resulted in being told there was an error and could not resolve it.

**Comment by codetaylor** [comment]
Tinkers parts use NBT data: `<tconstruct:pick_head>.withTag({Material: "wood"})`

This can be displayed with `/ct hand` while holding an item.

Info: https://docs.blamejared.com/1.12/en/#Vanilla/Items/IItemStack/#tag
Discord: https://discord.blamejared.com/
