### ISSUE TITLE
Disabling individual worktables in config does nothing.

### ISSUE THREAD

**Issue by SureenInk** [codetaylor/artisan-worktables#220]
Disabling individual worktables in the config doesn't actually disable the tables. I disabled the chemist, scribe, and tanner tables, yet they are still in JEI, still place-able, usable, etc. I kind of assumed disabling the individual worktables would remove them from the registry, but it seemed to do nothing at all.

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CraftTweaker: 1.12-4.1.20
* Artisan Worktables: 1.12.2-1.22.15
* Athenaeum: 1.12.2-1.17.4

**Comment by codetaylor** [comment]
JEI version please?

Disabling the tables does not remove them from the registry, it simply hides them in JEI as if you were to hide them in JEI with CrT. All tables must be registered because they are a single block with 15 variants.

**Comment by SureenInk** [comment]
Interesting, I'll have to double check then, but here's my JEI version. If you haven't duplicated before I have the chance to recheck it, I'll let you know if it still isn't working. It may be that I expected it to unregister and didn't pay attention to JEI itself (I usually grab stuff right out of the creative mode menu haha)

**Comment by codetaylor** [comment]
I think you forgot to include the JEI version.

**Comment by codetaylor** [comment]
Confirmed working as intended.
