### ISSUE TITLE
Ability to connect to a chest

### ISSUE THREAD

**Issue by Khris777** [codetaylor/artisan-worktables#222]
It would be great if the crafting tables had the ability to connect to a chest just like the Tinker's Crafting Station does, so when you're using the crafting table you can also take items from that chest directly.

**Comment by codetaylor** [comment]
Thank you for the suggestion. The mod already has the ability to connect to a Toolbox and a Mechanical Toolbox, both of which are provided by the mod. There is also an option in the configs to allow non-tool items into the toolboxes.

I will not be implementing this feature. This mod has already grown far beyond its original scope and I would like to spend my limited time working on other projects.
