### ISSUE TITLE
Exporting secondary output recipes only exporting 1 of each stack

### ISSUE THREAD

**Issue by SureenInk** [codetaylor/artisan-worktables#224]
When I try to export a recipe with a secondary output, it only exports one of each stack. I.e. if I tell it I want 6 string, it exports as 1 string.

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CraftTweaker: 4.1.20.562
* Artisan Worktables: 1.22.16-126-g90281c1
* Athenaeum: 1.17.4-9-g33cb77c

**Comment by codetaylor** [comment]
I'm not able to reproduce this.

Here's my setup:
![image](https://user-images.githubusercontent.com/1240716/79493793-d581bd80-7fd6-11ea-9287-f7d6968e93e5.png)

Here's the output for a shaped recipe:
```
RecipeBuilder.get("carpenter")
  .setShaped([
    [null, <minecraft:planks>, null],
    [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]])
  .addOutput(<minecraft:chest>)
  .setExtraOutputOne(<minecraft:log> * 4, 1.0)
  .setExtraOutputTwo(<minecraft:string> * 8, 1.0)
  .create();
```

**Comment by Chenjox** [comment]
I think he meant secondary **Ingredients** not Outputs.
This
![2020-04-16_20 40 58](https://user-images.githubusercontent.com/30270865/79494140-cd4f6f80-8022-11ea-9f30-f31d8d2265b2.png)

exports to this

`RecipeBuilder.get("basic")
.setShaped([[<minecraft:log>]])
.setSecondaryIngredients([<minecraft:stone>])
.addOutput(<minecraft:chest>)
.create();`

**Comment by codetaylor** [comment]
It looks like it's not working for secondary inputs. Did you mean secondary inputs?

![image](https://user-images.githubusercontent.com/1240716/79494270-943ddd80-7fd7-11ea-9526-212f2bdcfab4.png)

```
RecipeBuilder.get("carpenter")
  .setShaped([
    [<minecraft:planks>, null, null],
    [<minecraft:planks>, null, null],
    [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]])
  .setSecondaryIngredients([<minecraft:string>])
  .addOutput(<minecraft:chest>)
  .setExtraOutputOne(<minecraft:string> * 8, 1.0)
  .create();
```

**Comment by codetaylor** [comment]
Yeah, it's explicitly set to ignore count on those, but I don't remember if there was a reason or what I was thinking at the time. I'm going to go ahead and allow counts on those because I can't currently think of a reason not to.
