### ISSUE TITLE
Artisan Automation: Machines not setting hardness properly, and break instantly with bare hand

### ISSUE THREAD

**Issue by Bluberry-Kat** [codetaylor/artisan-worktables#228]
#### Issue Description
Both the Mechanical Artisan _and_ the Power Converter don't have their hardness set properly, and will break instantly even while holding nothing.
If the player is not holding a pickaxe, that means you lose your machine. Oh no!

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Artisan Automation: 1.12.2-1.0.0
* Athenaeum: 1.12.2-1.18.0

**Comment by codetaylor** [comment]
Thanks for the report! Fixed in version `1.0.1`
