### ISSUE TITLE
crash while initializing - athenaeum, artisan automation potential causes

### ISSUE THREAD

**Issue by RunDeckardRun** [codetaylor/artisan-worktables#230]
#### Intro

hello i'm trying to add Artisan Automation to  Dungeons, Dragons, & Space Shuttles V. 7.2b modpack which includes by default  artisan workbenchs, integration, and athenaeum.  i have updated athenaeum & artisan automation to their latest versions at time of writing (athenaeum-1.12.2-1.18.0  , artisanautomation-1.12.2-1.0.2) but crash during initialization

thank you for your time.

#### Issue Description

crashes during initialization, "an error during startup prevented minecraft from starting
the following mod(s)  have been identified as potential causes:
Athenaeum, Artisan Automation"

#### What Happens

minecraft crashes during initialization

#### What You Expect to Happen

minecraft modpack to load with added mod (artisinal automation)

#### Script

i have no idea how to check this, i did not add any script. 

#### Crash Log

https://paste.dimdev.org/ixoqosaqel.mccrash

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CraftTweaker: 1.12-4.1.20
* Artisan Worktables: 1.12.2-1.22.15
* Artisan Automation: 1.12.2-1.0.2
* Artisan Integrations: 1.12.2-1.2.0 
* Athenaeum: 1.12.2-1.18.0

**Comment by RunDeckardRun** [comment]
update: i've fixed it. 
updated artisan worktable from 1.12.2-1.22.15 to 1.12.2-1.23.0

have not updated artisan integrations. 
successfully loaded into world, hopefully in the clear now. 

thanks.

**Comment by codetaylor** [comment]
You should be in the clear. I just tested with your versions and was able to reproduce the error. Artisan Automation requires Artisan Worktables version 1.23.0 or greater to function. The latest Artisan Integrations is needed if you update Artisan Worktables and have Botania installed.

**Comment by codetaylor** [comment]
> The latest Artisan Integrations is needed if you update Artisan Worktables and have Botania installed.

Actually I think you might need it regardless of Botania.

**Comment by RunDeckardRun** [comment]
ah yes, the game had spat out a red herring but following it back to the source and updating that sorted it all out. 
one last question while i have you on the line, is the latest version of integrations 'Artisan Integrations: 1.12.2-1.2.0' ?
the pack does include botania and is having no issues with that version, but if there's a newer version i might as well just get the whole lot up to date! 

cheers

**Comment by codetaylor** [comment]
`1.2.1` is the latest

![image](https://user-images.githubusercontent.com/1240716/80926311-57017b80-8d4b-11ea-89a6-d96519991dc7.png)
