### ISSUE TITLE
Looking at "Mechanical Artisan" with HWYLA or Embers Goggles causes crash

### ISSUE THREAD

**Issue by SeriousCreeper** [codetaylor/artisan-worktables#233]
#### Issue Description

Using the mod HWYLA and looking at the mechanical artisan block (artisan automation) crashes the game. The same happens when looking at it with Ember Rekindled's Ashen Goggles.

#### Crash Log

HWYLA crash: https://pastebin.com/tFg1qHru
Embers Crash: https://pastebin.com/QbvE34iS
(also posted it here https://github.com/DaedalusGame/EmbersRekindled/issues/240) 

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CraftTweaker: 4.1.20.566
* Artisan Worktables: 1.23.0
* Artisan Automation: 1.0.2
* Artisan Integrations: 1.2.1
* Athenaeum: 1.18.0

**Comment by codetaylor** [comment]
Should be fixed in `1.0.3`
