### ISSUE TITLE
Auto Crafting gives out twice the recipe when first internal item matches the item output

### ISSUE THREAD

**Issue by SeriousCreeper** [codetaylor/artisan-worktables#234]
#### Issue Description

Bit of an odd one, basically when i use the auto crafter, and set it to Mode: Inventory (i havent tried "Keep" or "Manual" yet), whenever it crafts the item and tries to combine it with an existing stack inside the internal storage, it doubles the output. 

Video showcasing the issue: https://streamable.com/5pzuvu 

Hopefully that explains it a bit better. The same happens if i put 1 pipe into the first slot, then give it 2 ingots + 1 plate to craft 8 pipes. I end up with 17. 

EDIT: Just double checked Mode Keep and Manual, both behave properly (got 16 items after crafting twice), so it's only the Inventory mode.

#### Script

https://pastebin.com/02xiQCJX

#### Affected Versions

Do *not* use `latest`; please supply accurate version numbers.

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CraftTweaker: 4.1.20.573
* Artisan Worktables: 1.23.0
* Artisan Automation: 1.0.3
* Artisan Integrations: 1.2.1
* Athenaeum: 1.18.0

**Comment by codetaylor** [comment]
Thanks for the report! Should be fixed in `1.0.4`

**Comment by SeriousCreeper** [comment]
Thanks for the quick fix!
