### ISSUE TITLE
Recipes are voiding multiple itemstacks at once

### ISSUE THREAD

**Issue by Freebi85** [codetaylor/artisan-worktables#243]
I am currently testing the latest artisan version in conjunction with gregtech and have noticed that when crafting something while several items are in one slot, all of them are voided. (not sure if gregtech tools have any influence on that)
Made a small video about that.
[video.zip](https://github.com/codetaylor/artisan-worktables/files/4752211/video.zip)

```zs
recipes.remove(<waterstrainer:strainer_survivalist_solid>);

RecipeBuilder.get("blacksmith")
  .setShaped([
	[null, null, null, null, null], 
	[null, <ore:barsIron>, <ore:stickWood>, <ore:barsIron>, null], 
	[null, <ore:plateCurvedIron>, <waterstrainer:net:1>, <ore:plateCurvedIron>, null], 
	[null, <ore:barsIron>, <ore:stickWood>, <ore:barsIron>, null], 
	[null, null, null, null, null]])
  .setFluid(<liquid:lowgas> * 3000)
  .addOutput(<waterstrainer:strainer_survivalist_solid>)
  .addTool(<ore:artisansBurner>, 6)
  .addTool(<ore:craftingToolScrewdriver>, 6) 
  .addTool(<ore:artisansPliers>, 6) 
  .create();
```

* Minecraft: 1.12
* Forge: 14.23.5.2847 
* CraftTweaker: 8.1.9
* Artisan Worktables: 1.23.3
* Artisan Automation: 1.0.5
* Artisan Integrations:1.2.1
* Athenaeum: 1.18.1

**Comment by codetaylor** [comment]
Thanks for the report!

Should be fixed in `1.23.4`

**Comment by Freebi85** [comment]
Damn you’re so fast man. Thank you very much ♥️

**Comment by codetaylor** [comment]
You're welcome :)
