### ISSUE TITLE
Add more tools for the chef's worktable

### ISSUE THREAD

**Issue by Lord-Felidae** [codetaylor/artisan-worktables#245]
Personally, I love the crisp, shiny textures that these tools have, even when they're automatically generated they look phenomenal. There's just not that many for the chef's table, though.

I have a few suggestions, stuff like:

- Pots
- Saucepans
- Mixing bowls (and if they need to have contrast between the mortars, maybe style it like a white porcelain bowl with a stripe of the material below the rim)
- Oven sheets
(generally stuff that you would expect to see when you're cooking)

I was going to make this suggestion about other tables as well but I couldn't personally think of any. I understand that you're busy working on all of your mods, and that this may simply not happen.

**Comment by Xarmat-GitHub** [comment]
Pam's Harvestcraft use nice "Tools" for cooking.
Maybe get inspired by them.

Optional: Add durability to the Pam's Items, so they can be used with durability lose in Artisans.

(Not the room for that, but here is some extra - Mod Suggestion: Creat a Mod that can add Durability to Items that have none)

**Comment by codetaylor** [comment]
This is unlikely to be implemented because Artisan Worktables is now in 1.16. The 1.12 version will still receive fixes, but will not be receiving any new features.
