### ISSUE TITLE
Worktable Config File doesn't seem to affect worktable harvesting

### ISSUE THREAD

**Issue by BucketPro** [codetaylor/artisan-worktables#246]
#### Issue Description

Opening the module.Worktables config file and changing the harvest tool seems to have no effect on the tables actual harvest tool, regardless of tool chosen (aside from the default of pickaxe), the tool's harvest level, the table tier, or the kind of table chosen.

#### What Happens

1) Create a new creative world and place down any kind of table
2) Change the module.Worktables config file to set that table's harvest to to either axe or shovel
3) Restart Minecraft and acquire the necessary tool
4) Observe the table breaking slowly and not dropping anything
5) Acquire a pickaxe and observe the table breaking quickly and dropping when using the pickaxe

#### What You Expect to Happen

I expect the configured tool to harvest the table properly and for pickaxes to be less than ideal

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* Artisan Worktables: 1.12.2-1.23.4
* Athenaeum: 1.12.2-1.18.1

**Comment by codetaylor** [comment]
Thanks for the report!

This is fixed in `1.12.2-1.23.5`

**Comment by BucketPro** [comment]
Thanks for the quick fix. Everything is working fine.
