### ISSUE TITLE
Recipe Ordering

### ISSUE THREAD

**Issue by Ceifeire** [codetaylor/artisan-worktables#252]
* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CraftTweaker: 4.1.20.574
* Artisan Worktables: 1.23.2

Hi,

This is less of an issue and more of a question. I just made some recipes that use the tables provided in this mod, but when trying to view them in JEI the first "recipe" that appears is the enchantment options on the anvil. Is there a way to move this new custom recipe to be the first thing a player sees when clicking an item?

I have asked JEI about this as well just in case.

![JEI, artisan recipe issue](https://user-images.githubusercontent.com/38624271/92429227-47fa6200-f15f-11ea-8c53-d526c4e2fc87.png)

**Comment by codetaylor** [comment]
> Is there a way to move this new custom recipe to be the first thing a player sees when clicking an item?

AFAIK, there's nothing that can be done about that.

You're welcome to join the Discord, http://discord.codetaylor.com, if you have more questions.
