### ISSUE TITLE
wont let me put tools in tables

### ISSUE THREAD

**Issue by halie345** [codetaylor/artisan-worktables#253]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Minecraft:
* Forge:
* CraftTweaker:
* Artisan Worktables:
* Artisan Automation:
* Artisan Integrations:
* Artisan Workstumps:
* Athenaeum:

**Comment by halie345** [comment]
it wont let me put the needle in the tailor table and wont let me put the wooden knife in workshop table? what do i do? im playing singleplayer

**Comment by Chenjox** [comment]
Have you defined recipes via Crafttweaker where said tools are needed?

**Comment by codetaylor** [comment]
Only tools that are defined in recipes using CraftTweaker are allowed to be inserted into tables.
