### ISSUE TITLE
Recipes with more than one item in a slot fail

### ISSUE THREAD

**Issue by democat3457** [codetaylor/artisan-worktables#255]
## Expected Behavior

Recipes that specify multiple items in one slot should remove that number of items from the slot when the output is taken out.

## Current Behavior

Recipes that specify multiple items in one slot will only work if there is the specified amount in that slot, but the recipes will only remove one item from that slot. It is similar to vanilla's method of handling multiple items in one slot as well.

## Steps to Reproduce (for bugs)

1. Add any crafting recipe via CrT that has an item with an amount greater than one in a slot.
2. Put that number of items into one slot and observe that the output shows.
3. Take out the output, observe that the number of items only goes down by one.

## Script

https://haste.antti.codes/lagiworeti.less

## Your Environment

* Minecraft: 1.12.2
* Forge: 14.23.5.2847
* CraftTweaker: 4.1.20.613
* Artisan Worktables: 1.24.0
* Artisan Integrations: 1.2.2
* Artisan Workstumps: 1.1.2
* Athenaeum: 1.19.2

**Comment by codetaylor** [comment]
The current behavior is the expected behavior.

AW is designed to be used with recipes that specify only one ingredient per slot in the crafting grid. It does, however, allow multiple ingredients in the secondary ingredient slots.

I do not intend to change this behavior.
