### ISSUE TITLE
[SUGGESTION] 4x4 Crafting Pattern

### ISSUE THREAD

**Issue by Xarmat-GitHub** [codetaylor/artisan-worktables#258]
# Description
- Change the Crafting Grid of the "Workstations - Tier 2" from 3x3 to 4x4
- Add the "Secondary Ingredients " bar to the "Worktables - Tier 1"

# Reasons
- Have a nice scaling from tier to tier:
- - 3x3 / 4x4 / 5x5
- - 1 tool / 2 tools / 3 tools
- - all support Secondary Ingredients (USP main feature)
- - all support Fluids (USP main feature)

# Story
I thought about using tier levels to give the player a feel of progression, but I get limited by grid size and/or the lack to use secondary ingredients.

I have something like this in mind:
- Tier 1 Blacksmith: Small Basic Weapons (Commoner Class Weapons) 3x3 - Knives, Club, etc.
- Tier 2 Blacksmith: Medium Weapons (Adventurer / Fighter Weaponry) 4x4 - Sword, Mace, etc.
- Tier 3 Blacksmith: Large Weapons (War Weapon Class) 5x5 - Great Sword, War Hammer, etc.
- Extra: In my Mod Pack, the player not only need the main parts from the weapons (blade part, hand guard, etc. - Tinkers) he also needs metal nuggets / leather and so on to craft these weapons

At the given moment, the Tier 1 Table can not give me secondary ingredients support
The Tier 2 Table has only a 3x3 grid (only useable for "Commoner Class Weapons", no room for 4x4 Fighter Weapons)
So I decided to put all recipes into the Tier 3 Table, what is a shame... because I can not use the other tiers nicely for player progression.

# Ticket End
Maybe you see the opportunities the three tier level can have with a bit of changes.
By add and make thing bigger, it would not destroy recipes / mod packs.
I can understand the "Tutorial" Part of: "Learn about Tools" -> "Learn about secondary ing." -> "Learn about grid size". But Modpack Makers can use simple tools to give the players the right informations to learn them.

Thanks for reading and the nice mod so far. 👍

**Comment by Xarmat-GitHub** [comment]
I think it can break Modpacks that update the Mod Version without checking the 4x4 crafting recipes.
There is a chance that recipes that are not exactly set (by tier) can be crafted earlier in the game.
But I am not sure about that... as far I understand it, new recipes will be add to Tier 3 Tables as long there is not a clear definition of setMinimumTier / setMaximumTier.

**Comment by codetaylor** [comment]
I can appreciate the time and thought you have put into your design suggestion, however it won't be changed for the following reasons:

1. Artisan Worktables is now in 1.16 and the 1.12 version will still receive fixes, but will not be receiving any new features,
2. To pivot the design at this stage of development would require far more of my time and effort than is worth to me, and
3. This change in design would not fit with what I need the mod to do.
