### ISSUE TITLE
Recipes don't work on server

### ISSUE THREAD

**Issue by AffectAge** [codetaylor/artisan-worktables#260]
## Current Behavior
Recipes created with Artisian Worktables don't work in multiplayer.

## Script
Line 45
https://pastebin.com/RW38PPQM

## Log
https://pastebin.com/XXUTkvK7

## Your Environment

* Minecraft: 1.12.2
* Forge: 14.23.5.2854
* CraftTweaker: 4.1.20.635
* Artisan Worktables: 1.24.0
* Artisan Automation: -
* Artisan Integrations: 1.2.2
* Artisan Workstumps: -
* Athenaeum: 1.19.2

**Comment by AffectAge** [comment]
https://pasteboard.co/JYXmckl.png

**Comment by codetaylor** [comment]
I've never encountered this problem with a server before. I don't know what could be causing it yet.

**Comment by codetaylor** [comment]
![image](https://user-images.githubusercontent.com/1240716/116125386-46dc5d80-a67a-11eb-8e6f-c81f2b67e79d.png)

The error indicated here, `ERROR: Recipe input already set` indicates that you're calling the method `setIngredients` twice on the same recipe builder.

Please link your CraftTweaker log file, `pyrotech.zs`, and `minecraft.zs`.

**Comment by AffectAge** [comment]
[crafttweaker.log](https://github.com/codetaylor/artisan-worktables-1.12/files/6379029/crafttweaker.log)

[minecraft.txt](https://github.com/codetaylor/artisan-worktables-1.12/files/6379032/minecraft.txt)
[pyrotech.txt](https://github.com/codetaylor/artisan-worktables-1.12/files/6379033/pyrotech.txt)

**Comment by AffectAge** [comment]
Caused by: java.lang.RuntimeException: Attempted to load class bud for invalid side SERVER
	at net.minecraftforge.fml.common.asm.transformers.SideTransformer.transform(SideTransformer.java:60)
	at net.minecraftforge.fml.common.asm.ASMTransformerWrapper$TransformerWrapper.transform(ASMTransformerWrapper.java:252)

**Comment by codetaylor** [comment]
Thank you. I've been able to track down the cause and reproduce the issue. It's a problem with Artisan Integrations. I should have it fixed soon.

**Comment by codetaylor** [comment]
Should be fixed in Artisan Integrations `1.12.2-1.2.4`

**Comment by AffectAge** [comment]
Thanks to you, my player can't play without instruments)) I love you mods
