### ISSUE TITLE
Artisan Integrations crashing with GTCEu's tools

### ISSUE THREAD

**Issue by AzraelBunn** [codetaylor/artisan-worktables#262]
## Expected Behavior
Recipe working correctly.

## Current Behavior
Minecraft freezes when putting all the ingredients and tools in. The game crashes but doesn't close.

## Steps to Reproduce (for bugs)
1. Create a recipe using any of the GTCEu's tool.
2. Try crafting it.

## Script
Anything using stuff like `.addTool(<ore:craftingToolKnife>, 5)` or `.addTool(<metaitem:tool.knife>, 5)`.

## Crash Log
https://pastebin.com/vyiVchWq

## Your Environment
* Minecraft: 1.12.2
* Forge: 14.23.5.2860
* CraftTweaker: 4.1.20.674
* Artisan Worktables: 1.24.2
* Artisan Integrations: 1.2.4
* Athenaeum: 1.19.5
* GTCEu: 2.1.2-beta

**Comment by codetaylor** [comment]
Thanks for the report!

This is probably happening because the GTCE API has changed - I'll look into it when I have some time.

**Comment by codetaylor** [comment]
Ok, this is not a bug.

Artisan Integrations was built against the [GTCE API](https://github.com/GregTechCE/GregTech/blob/master/src/main/java/gregtech/api/items/IToolItem.java#L17), not the [GTCEu API](https://github.com/GregTechCEu/GregTech/blob/master/src/main/java/gregtech/api/items/IToolItem.java#L18).

For now, Artisan Integrations will only support [this version of GTCE](https://www.curseforge.com/minecraft/mc-mods/gregtechce).

**Comment by AzraelBunn** [comment]
Would be nice if you also added GTCEu support as it is just a better version of GTCE with people that care about modpack makers working on it.

**Comment by codetaylor** [comment]
@TheNextJake Test this: [artisanintegrations-1.12.2-1.2.4-1-g16df843.zip](https://github.com/codetaylor/artisan-worktables-1.12/files/8199895/artisanintegrations-1.12.2-1.2.4-1-g16df843.zip)

**Comment by AzraelBunn** [comment]
It's working so far.
If something happens again should i keep it here?

**Comment by codetaylor** [comment]
Thank you for testing.

> If something happens again should i keep it here?

If there is a problem, please create a new issue here on GitHub.
