### ISSUE TITLE
Large number of player levels prevents crafting

### ISSUE THREAD

**Issue by phoenixf1re** [codetaylor/artisan-worktables#264]
## Expected Behavior
the recipe should be visible and craftable even if you have more than 15465 XP (level)

## Current Behavior
the recipes vanishs if you have more than 15465 xp LEVEL 
## Steps to Reproduce (for bugs)

1. create a recipe
2.start the game 
3.give yourself 154*66* LEVEL ( /xp 15466L  
4.open the specified table/bench/station (in survival)
5.put the items for the recipe in the table
6.notice that there is absolutely nothing in the output slot
7. remove one xp level (/xp -1L)
8. the recipe is back and you can craft it

## Script

https://cdn.starfiles.co/files/7297e76974b437a70821790ab337ca95e33152641a18b92d119ef9839821e42b/basicworktable.txt

## Your Environment

* Minecraft:
* Forge:14.23.5.2854 and 2859 and 2860
* CraftTweaker2:4.1.20.675 
* Artisan Worktables:1.24.2
* Artisan Automation:1.0.6
* Artisan Integrations:1.3.0
* Artisan Workstumps:-----
* Athenaeum:1.19.5
* just enough items:4.16.1.301
* jei-integrations:1.6.0

**Comment by codetaylor** [comment]
https://discord.com/channels/516841320594276353/516847501526171658/992826294381318274

**Comment by codetaylor** [comment]
Reproduced using:

```
import mods.artisanworktables.builder.RecipeBuilder;

RecipeBuilder.get("basic")
  .setShaped([
    [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>],
    [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>],
    [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]])
  .addTool(<artisanworktables:artisans_hammer_diamond>, 1)
  .addOutput(<minecraft:diamond>)
  .create();
```

**Comment by codetaylor** [comment]
New limit is the same as MC's limit of `21863` levels and roughly `6.6` bars for a total of `2147483647`, max signed int, experience.
