### ISSUE TITLE
Request: Chemist's Worktable

### ISSUE THREAD

**Issue by septemberWaves** [codetaylor/artisan-worktables#27]
Title of this request is fairly self-explanatory. A chemistry-themed worktable; tools which I would suggest might be things like a flask, test tube, or burner. Request is primarily because I think a dedicated worktable for chemistry would make sense in the early-game of my modpack, but I think other modpack developers could make good use of it too.

**Comment by codetaylor** [comment]
I think this is a great idea! It will probably work its way into a future update. :)

**Comment by codetaylor** [comment]
Soon(tm).

![image](https://user-images.githubusercontent.com/1240716/35174756-5ffcab50-fd25-11e7-99cb-f62a2742d8b1.png)

**Comment by codetaylor** [comment]
Available in 1.12.2-1.9.16
