### ISSUE TITLE
Advanced Worktables

### ISSUE THREAD

**Issue by Xaikii** [codetaylor/artisan-worktables#29]
Meanwhile the current Tables are already pretty nice and effective, I'd personally prefer having more these tables also with more slots(Maybe as an add-on(ExtendedCrafting + Artisan-Worktables)). 3x3 can be used pretty well but I think tables like 5x5-9x9 can increase the usages pretty much especially for detailed recipes :)

**Comment by codetaylor** [comment]
I like the idea, but I'll be honest, it will probably be a while before I have time to implement more feature requests.

Thank you for your suggestion. :)

**Comment by Xaikii** [comment]
Take your time buddy ^^ you are already adding pretty cool stuff :D 
also it's not hurry, I can wait :P

**Comment by codetaylor** [comment]
![image](https://user-images.githubusercontent.com/1240716/36347145-d85081d0-1404-11e8-93e6-ebf0fa1fa941.png)

Available in 1.12.2-1.15.23

**Comment by Xaikii** [comment]
Thanks :)
but won't you go beyond 5x5?

**Comment by codetaylor** [comment]
No.
