### ISSUE TITLE
CTGUI support

### ISSUE THREAD

**Issue by erindal** [codetaylor/artisan-worktables#34]
I know you've said it'll be a while before you can implement any more suggestions, but I thought I would throw this out there.

https://crafttweaker.readthedocs.io/en/latest/#Vanilla/CTGUI/

If this is already there, I didn't see it in the documentation anywhere.

Your mod is amazing, keep up the great work!

**Comment by codetaylor** [comment]
Thank you for the compliment. Having a graphical UI to design recipes would be a great addition to the mod and I can see how it would be very useful for many people. That being said, functionality for creating recipes already exists via ZenScript scripting. The CTGUI feature, as nice as it would be to have, adds a different way of achieving something that can already be done and, in that respect, is redundant. Unfortunately, when allocating my already limited time to feature development for this project, other features that implement new functionality will take precedence.
