### ISSUE TITLE
doing a craft tweaker script in the basic worktable as a 3x3 resapie isn't working

### ISSUE THREAD

**Issue by Nathan22211** [codetaylor/artisan-worktables#36]
I tried to make a crafting resapie for the chest in the basic worktable I did this

```
import mods.artisanworktables.Worktable;

import mods.artisanworktables.IRecipeBuilder;

Worktable.createRecipeBuilder("basic")
    .setShaped([
        [<ore:logWood>, <ore:nuggetIron>, <ore:logWood],
        [<ore:planksWood>, null, <ore:planksWood>],
        [<ore:logWood>, <ore:planksWood>, <ore:logWood>]])
    .setTool(<primal:flint_saw>, 12)
    .addOutput(<minecraft:chest>)
    .create();
```

I don't if it's a bug or if it's because your mod doesn't allow 3x3 resapies in the crafters.

**Comment by Intipablo** [comment]
You're missing this Import: import mods.artisanworktables.Worktable;

And basically, all your items need to be surrounded using these brackets: <>

EDIT: apparently they remove those brackets when you put them here, just make sure you're using the right brackets around everything. Oh and by the way, brackets don't go around "null".

**Comment by codetaylor** [comment]
Also, it's `ore:plankWood` not `ore:planksWood`.

```
import mods.artisanworktables.Worktable;

Worktable.createRecipeBuilder("basic")
.setShaped([
    [<ore:logWood>, <ore:nuggetIron>, <ore:logWood>],
    [<ore:plankWood>, null, <ore:plankWood>],
    [<ore:logWood>, <ore:plankWood>, <ore:logWood>]])
.setTool(<primal:flint_saw>, 12)
.addOutput(<minecraft:chest>)
.create();
```

Also, have a look in your `crafttweaker.log` file. It usually gives you clues as to what's wrong.
