### ISSUE TITLE
basic worktable dosn't seen to be working

### ISSUE THREAD

**Issue by Nathan22211** [codetaylor/artisan-worktables#37]
about the one I did previsely. explan this 
![2018-01-26_12 13 37](https://user-images.githubusercontent.com/35241068/35454301-17bae924-0293-11e8-8fb2-a21806c0443c.png)

**Comment by Nathan22211** [comment]
I used the same craft tweaker script with the fix to the ore driect and it isn't showing in JEi

**Comment by codetaylor** [comment]
Forge: 14.23.1.2594
Artisan Worktables: 1.9.17
Athenaeum: 1.5.3
CraftTweaker: 4.1.0
JEI: 4.8.5.147
PrimalCore: 0.6.17

Using script:

```
import mods.artisanworktables.Worktable;

Worktable.createRecipeBuilder("basic")
.setShaped([
    [<ore:logWood>, <ore:nuggetIron>, <ore:logWood>],
    [<ore:plankWood>, null, <ore:plankWood>],
    [<ore:logWood>, <ore:plankWood>, <ore:logWood>]])
.setTool(<primal:flint_saw>, 12)
.addOutput(<minecraft:chest>)
.create();
```

![image](https://user-images.githubusercontent.com/1240716/35454874-a2a9bf06-0284-11e8-8a71-3a8381fdb45f.png)

Tell me what versions you are using. Also, post a link to your `crafttweaker.log` file. Post it as a gist or on pastebin, don't paste it as a comment here.

**Comment by codetaylor** [comment]
Also tested with Forge 14.23.1.2604 and it works fine.

**Comment by Nathan22211** [comment]
i'm using craft tweaker  4.0.12

artesian worktables 1.9.17

and antehinm 1.5.3

**Comment by Nathan22211** [comment]
and here's the log 
```
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Building registry
[INITIALIZATION][CLIENT][INFO] CraftTweaker: Successfully built item registry
[INITIALIZATION][CLIENT][INFO] Loading scripts
[INITIALIZATION][CLIENT][INFO] [crafttweaker | SIDE_CLIENT]: Loading Script: {[0:crafttweaker]: test.zs}
[POSTINITIALIZATION][CLIENT][INFO] Altering RecipeWorktable Recipe(s) for "basic"
[SERVER_STARTED][CLIENT][INFO] Fixed the RecipeBook
```

**Comment by Nathan22211** [comment]
it wasn't that big

**Comment by codetaylor** [comment]
Try updating CraftTweaker to the latest version.

Can you show me the script you are using?

**Comment by Nathan22211** [comment]
this is what I used 
```
Worktable.addRecipeShaped("basic", <minecraft:chest>, <primal:flint_saw>, 12, true, [
    [<ore:logWood>, <ore:nuggetIron>, <ore:logWood],
    [<ore:plankWood>, null, <ore:plankWood>],
    [<ore:logWood>, <ore:plankWood>, <ore:logWood>]]);
``` 
let me see if it works in the table might be a bug with JEI

**Comment by Nathan22211** [comment]
well I am using a older JEI version but the crafting is not working

**Comment by codetaylor** [comment]
Ok, I was able to reproduce the issue. It's because your script is missing one of these `>`.

**Comment by codetaylor** [comment]
The parsing and reporting of errors like that is done in CraftTweaker and is, unfortunately, out of my control.

**Comment by Nathan22211** [comment]
so either my script is wrong or there's a but with craft tweaker

**Comment by Nathan22211** [comment]
oh wait I just saw the commet

**Comment by Nathan22211** [comment]
well this is embarresing

**Comment by codetaylor** [comment]
No worries. I hope it works for you. :)
