### ISSUE TITLE
Craft without tool

### ISSUE THREAD

**Issue by okid0kii** [codetaylor/artisan-worktables#50]
Hi.
How can i do a craft without tool in the basic worktable for exemple. I try:

Worktable.addRecipeShapeless("basic", <minecraft:planks>, null, 0, [<ore:logWood>]);

But it don't like that ^^

**Comment by codetaylor** [comment]
At this time there is no way to perform a craft without a tool. I may add this in the future.

**Comment by codetaylor** [comment]
Available in alpha 1.12.2-1.15.25-21-g825ea34

Will be available in beta 1.12.2-1.16.x
