### ISSUE TITLE
question for ya lol

### ISSUE THREAD

**Issue by CharCharthemonkey** [codetaylor/artisan-worktables#54]
hypothetical question but if some1 wanted to make a recipe from 1 mod using one of the tables in ure mod but keep it the same as that mod recipe except in ure table how would they do that?

**Comment by codetaylor** [comment]
Use CraftTweaker:
http://crafttweaker.readthedocs.io/en/latest/#
https://github.com/codetaylor/artisan-worktables/blob/master/ZENSCRIPT.md
https://github.com/codetaylor/artisan-worktables/blob/master/ZENSCRIPT_ADVANCED.md
