### ISSUE TITLE
[Enhancement] Some ideas

### ISSUE THREAD

**Issue by JWTHDYTWA** [codetaylor/artisan-worktables#57]
1. I think it's good idea to make mage's worktable require bookshelves and XP levels.¹
2. Automatic worktables that uses RF/FE/IE/Tesla/Mana/Fuel to work.
3. Add blueprints that are required if it set in CraftTweaker script (contains recipe name in NBT) (it's easy to tweak its recipe or spawn as loot).
4. Add Fluxed Electrum (from RedstoneArsenal) tools.

¹ It's important to not forget custom enchanting boosters (e.g. Botania pylons, EU2 magical wood)

**Comment by codetaylor** [comment]
Thank you for sharing your ideas.

Please see the new feature suggestion guidelines in the README.md displayed on the repository's front page.
