### ISSUE TITLE
Workstation shows wrong internal tank capacity

### ISSUE THREAD

**Issue by MasterEnderman** [codetaylor/artisan-worktables#62]
#### Issue Description

The Workstation doesn't show the correct max fluid amount.

#### What Happens

https://imgur.com/BmJREbA

#### What You Expect to Happen

It shows the correct max fluid amount.

#### Script

https://pastebin.com/b8RjF2yQ

#### Config

https://pastebin.com/pigA9kwd

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.2.2613
* CraftTweaker: 4.1.2
* Artisan Worktables: 1.14.22
* Athenaeum: 1.9.5

**Comment by codetaylor** [comment]
Good catch, thanks!
