### ISSUE TITLE
Add syntax highlighting to CraftTweaker documentation

### ISSUE THREAD

**Issue by ChiriVulpes** [codetaylor/artisan-worktables#66]
Currently there is no syntax highlighting for the ZenScript examples in the CraftTweaker documentation.  
https://github.com/codetaylor/artisan-worktables/blob/master/ZENSCRIPT.md  
https://github.com/codetaylor/artisan-worktables/blob/master/ZENSCRIPT_ADVANCED.md  

There obviously isn't syntax support for ZenScript in GitHub, but you can use a similar language to provide the syntax highlighting. I suggest JavaScript. Here's an example of what ZenScript looks like with JavaScript syntax highlighting: https://github.com/Yuudaari/soulus/blob/master/docs/CRAFTTWEAKER.md

**Comment by codetaylor** [comment]
This will be fixed when b12fc4adb7144b9f30c57c758bda066936b2b054 merges into the master branch.
