### ISSUE TITLE
Add a readme description for the "tool damage" argument of addTool

### ISSUE THREAD

**Issue by ChiriVulpes** [codetaylor/artisan-worktables#67]
This isn't a huge deal, as it's very easy to figure out what it does (since it shows the information in the JEI recipe view), but currently the [ZenScript documentation](https://github.com/codetaylor/artisan-worktables/blob/master/ZENSCRIPT_ADVANCED.md) has no description of what the `int damage` argument of `addTool` is used for. I initially assumed it was for how much durability the tool had to have left.

**Comment by codetaylor** [comment]
This will be fixed when b12fc4adb7144b9f30c57c758bda066936b2b054 merges into the master branch.
