### ISSUE TITLE
Add a Worktable for food

### ISSUE THREAD

**Issue by ChiriVulpes** [codetaylor/artisan-worktables#71]
I'm surprised this one doesn't exist already. A worktable for food (such as a Chef's Worktable) would be a welcome addition. There could also be many tools for it, such as pots, pans, ladles, whisks, knives, and even a rolling pin. I understand you might want to stick to the two tools per table theme, however.

**Comment by codetaylor** [comment]
This has been a low priority since Cooking for Blockheads and Pam's Harvestcraft is such a potent combination. I do plan to get around to it at some point.

**Comment by ChiriVulpes** [comment]
I would use Pam's, but never Cooking for Blockheads because it's not "Minecrafty" (which is the most important part of modded for me, I guess I'm kinda superficial). And Pam's alone is kinda sad because of the way it does recipes with water (the water item). I'm not using Pam's currently, but I'm doing the same thing with my recipes (for instance, making a "dough" using flour and water requires grabbing a bucket of water for each craft.), and that's the main reason I'm disappointed in there not being a food worktable, actually. I guess I can retexture a worktable I'm not using yet for a food worktable right now tho.

**Comment by codetaylor** [comment]
Yeah, then send me the textures. :P

The biggest time sink for adding new tables is the texture design.

**Comment by ChiriVulpes** [comment]
Your textures are so good tho! They're creative and really pretty, I don't think I can do as good as you. I could send you whatever I make and you could prettify it, I guess ¯\\\_(ツ)\_/¯

**Comment by codetaylor** [comment]
![image](https://user-images.githubusercontent.com/1240716/36837845-54859ae2-1cf2-11e8-887c-dfa13c84a28c.png)
