### ISSUE TITLE
Support changing the text shadow colour

### ISSUE THREAD

**Issue by ChiriVulpes** [codetaylor/artisan-worktables#75]
This will allow resourcepacks and modpack resource overrides to change the textures of default worktables without having the text look weird.

![Chef's Worktable](https://puu.sh/zpIJF/bb24295b0c.png)

In this example I actually switched the carpenter's texture over to the chemist worktable, but I can't change the colour of the fluid highlights or text. (I'm actually editing most of the textures in order to tier them more with the items they're made from and make their appearances match their items)

This would be the easiest to work with if done via colour sampling (like grass/foliage colourmaps) from the gui files. (EG: using a pixel below the gui in the worktable's image). Not sure how easy that would be to implement, tho. I haven't looked into how colourmaps work.

**Comment by codetaylor** [comment]
It would be easier and less time consuming for me to implement as config values. Maybe hex values, like web colors. It could be changed in real time that way without reloading anything.

**Comment by codetaylor** [comment]
Can now edit the highlight color in the config file, or the config menu in-game:

![image](https://user-images.githubusercontent.com/1240716/36357985-5c80a9ce-14bb-11e8-89b9-f951de096596.png)

Available in next alpha snapshot and / or beta 1.16.x

**Comment by codetaylor** [comment]
Available in the alpha snapshot 1.12.2-1.15.25-10-gcce9f8f

Will be available in the beta 1.12.2-1.16.x
