### ISSUE TITLE
Remove profession distinction from tool names

### ISSUE THREAD

**Issue by codetaylor** [codetaylor/artisan-worktables#76]
If the profession distinctions were removed from tool names, it would lift thematic restriction and promote the use of some tools across professions. Take the chisel for example. It could be used in the Mason's, Carpenter's, or the Jeweler's table. Since it is currently named Mason's Chisel, it feels thematically awkward to use the chisel in a Carpenter's table.

Before I make this change, I'd like others to weigh in with opinions. Please let me know what you think.

**Comment by codetaylor** [comment]
If I remove the profession distinction from tool names, it's likely that the ore dict entry keys for the tools will also be renamed. So instead of `mages_athame`, it would be `toolAthame`. The prefix `tool` could be set in the config file to avoid potential conflicts.

This would be a breaking change, but I don't think it would be too inconvenient. A simple folder-wide search and replace would clear it right up.

**Comment by BismuthBorealis** [comment]
I think it fits with the current set of changes being implemented in 1.16.x, it's an awesome idea!

Edit; Just realised there are two tools called hammers, would you keep the profession distinction in that case, change what the distinction is, or remove one of them?

**Comment by codetaylor** [comment]
My idea was to rename the `Blacksmith's Hammer` to `Hammer` and the `Carpenter's Hammer` to `Framing Hammer`. A more generalized alternative to `Framing Hammer` could be `Small Hammer`. I am open to discussion.

**Comment by BismuthBorealis** [comment]
I was imagining `Small Hammer`, but I think `Framing Hammer` is better.

**Comment by codetaylor** [comment]
Available in alpha 1.12.2-1.15.25-21-g825ea34

Will be available in beta 1.12.2-1.16.x
