### ISSUE TITLE
Workshop tabs are cut off at the top when the window size is small.

### ISSUE THREAD

**Issue by codetaylor** [codetaylor/artisan-worktables#77]
![image](https://user-images.githubusercontent.com/1240716/36347057-63ca9820-1402-11e8-9351-029cf61e5dca.png)

**Comment by codetaylor** [comment]
Use a larger window? Use a smaller resolution?

¯\\_(ツ)\_/¯

**Comment by TheMysticalBard** [comment]
You can also just change the GUI Scale in the vanilla Minecraft video settings to fix this.
