### ISSUE TITLE
NoClassDefFoundError: com/codetaylor/mc/artisanworktables/modules/worktables/gui/GuiContainerBase

### ISSUE THREAD

**Issue by ChiriVulpes** [codetaylor/artisan-worktables#78]
#### Issue Description

Workshops don't behave correctly on a server. They can't be broken and their GUI can't be opened.

#### What Happens

Worktables and Workstations behave correctly: They can be placed and broken. Workshops can't. When a Workshop is placed, it runs what I assume is client-side code on the server, as the server logs the NoClassDefFoundError for the GuiContainerBase class. Once the block is placed, it can't be broken. It will break on the client but not on the server. Relogging or placing another block in its place will restore it. You also can't right click on the Workshop to open its GUI; the same error is logged. See "Crash Log" section below.

#### Script

None.

#### Crash Log

Doesn't actually crash, but this error is what is printed whenever you try to interact with the Workshop.

https://puu.sh/zqrX3/76fd52d95e.txt

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 14.23.2.2618
* CraftTweaker: 1.12-4.1.4
* Artisan Worktables: 1.12.2-1.15.23
* Athenaeum: 1.12.2-1.9.5

**Comment by codetaylor** [comment]
I tested this.

-.-

(╯°□°）╯︵ ┻━┻

**Comment by codetaylor** [comment]
Nothing a few sprinkles of `@SideOnly(Side.CLIENT)` can't fix, right?

**Comment by codetaylor** [comment]
Fixed in 1.12.2-1.15.24
