### ISSUE TITLE
Crafting Tweaks integration

### ISSUE THREAD

**Issue by hron84** [codetaylor/artisan-worktables#80]
Could you add a CraftTweaker integration (whatever is needed for it) for the tables? CraftTweaker is basically lets you rebalance, rotate, and remove items in the crafting grid.

**Comment by Xaikii** [comment]
This mod works primarily with CraftTweaker, it just works different than others. [ZenScript](https://github.com/codetaylor/artisan-worktables/blob/master/ZENSCRIPT.md)

**Comment by thephoenixlodge** [comment]
By the sounds of it you mean Crafting Tweaks, not Crafttweaker.

**Comment by codetaylor** [comment]
@hron84 For future feature requests, please follow the feature request submission guidelines on the front page of this repo.

Do you in fact mean to say **Crafting Tweaks** and not **CraftTweaker**?

If so, where do you suggest I place the three Crafting Tweaks buttons?

![image](https://user-images.githubusercontent.com/1240716/36396227-cfd782ec-1571-11e8-92b8-aaeacd49a0c9.png)

**Comment by Xaikii** [comment]
According to the description he gave afterward it's 100% sure that he meant Crafting Tweaks ^^'

**Comment by hron84** [comment]
@codetaylor yeah, it was a typo, I mean Crafting Tweaks.

About buttons: I have no idea how Crafting Tweaks works, maybe it will place the buttons on its own. But all mods that supported by that mod placed the button left from the grid, this is common across most supported mods.

**Comment by codetaylor** [comment]
Thank you for the suggestion, however I won't be implementing this.

This mod has already grown far beyond its original scope and I would like to spend my limited time working on other projects.

**Comment by hron84** [comment]
@codetaylor I'm sad to read this. Does it mean you plan to abandon this project or you will hand over its development for someone? Because if the latter is true, I'd rather see keep this ticket open as it's still an issue and maybe the new developer would have a time for integration.

**Comment by codetaylor** [comment]
No, I am not abandoning this project and I am not giving it to someone else.

**Comment by codetaylor** [comment]
This has been implemented and will be available in the next release `1.23.0`.

The only button that won't be available is the rotate button for the large 5x5, but all the other buttons work on all the tables. I may implement the 5x5 rotation someday, but I just can't think of a good way to do it right now due to the fact that the outer 'track' of the crafting matrix is larger than the inner 'track'.

![image](https://user-images.githubusercontent.com/1240716/79287438-a9502a80-7e78-11ea-89ff-7afe6cd95f95.png)

**Comment by hron84** [comment]
Thanks, 3x3 crafting is far enough, I use this a lot in them since I always forget the location of items in some recipes.
