### ISSUE TITLE
CraftTables TAB

### ISSUE THREAD

**Issue by okid0kii** [codetaylor/artisan-worktables#86]
Hello.

#### What Happens

When all artisanworktables (ex: lvl1) are side by side the last TAB makes us leave the craft tables.
We need to click first to access the GUI on the first table. When we click first on the 5th table the problem dissapear.

In the right order (the order tab) the last two. And in any order it's random.

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 1.12.2 - 14.23.2.2611
* CraftTweaker: 1.12-4.1.4
* Artisan Worktables: 1.12.2-1.15.26
* Athenaeum: 1.12.2-1.11.6

**Comment by codetaylor** [comment]
If you are too far away from a table, you can't use the table. For example, if I line up all the tables and stand too far away from some of the tables, those tables won't be usable, even when you switch to the tab in the gui.

If I place all 10 tables down in a row and stand at the first table I can't reach the last table to open the table's gui. The tabs work with the same limitations. If you switch to the tab of a table that you can't normally reach, you can't open the gui. Just like if you stood too far away from a vanilla crafting table and tried to click on it: you can't.

This is the proper behavior.

Edit: If you place all 10 tables in a row and stand in the middle, you can access all 10 tables via the tabs.

**Comment by codetaylor** [comment]
I've made some changes to help address this issue. If you are too far away from a table to use it, its tab will no longer show in the gui. Also, if you are too far away from the toolbox to interact with it, its gui will no longer show adjacent to the worktables gui. The mechanical toolbox will still work to swap tools even if you are too far away to access its gui.
