### ISSUE TITLE
Blueprints for automation

### ISSUE THREAD

**Issue by lobbienjonsji** [codetaylor/artisan-worktables#87]
Could it be possible to make a blueprint item, which can be put into a certain slot, and then configured to put the items inot a certain order?

**Comment by lobbienjonsji** [comment]
Just read in the changelog about automation being added in the future eventually. Thank you!

**Comment by codetaylor** [comment]
I've got some ideas for automation and the implementation will most likely utilize a blueprint item in some way.

**Comment by belathus** [comment]
Allowing automation in the Artisan Worktables would remove a lot of my apprehension from using them more.

**Comment by codetaylor** [comment]
Available in the mod Artisan Automation
