### ISSUE TITLE
Botania Tools

### ISSUE THREAD

**Issue by Tedyhere** [codetaylor/artisan-worktables#9]
Can you add Manasteel/Terrasteel/Elementium versions of tools? I think it would make sense to have magical metal tools to craft magical items.

**Comment by codetaylor** [comment]
Absolutely, that's a good idea!

**Comment by codetaylor** [comment]
Implemented in 148025197ceb94f297f45e2ddb395c8f575ba1fc

Will be in next release! Thanks for the suggestion.

**Comment by codetaylor** [comment]
Available in version 1.12.2-1.5.8
