### ISSUE TITLE
Pottery Table?

### ISSUE THREAD

**Issue by Habeeb-M** [codetaylor/artisan-worktables#91]
Works well for Ceramic's items, not really suited to any other workbench, ~~and is balanced since its used for clay~~.

**Comment by codetaylor** [comment]
That's a good idea, I'll keep that in mind.

What kind of tools do you think would go with it?

**Comment by Habeeb-M** [comment]
Something like a [clay cutter](https://www.google.co.uk/search?rlz=1C1CHBF_en-GBGB777GB777&biw=681&bih=642&tbm=isch&sa=1&ei=H-SsWq36MMuWsgHGlKeoDw&q=clay+cutter+with+string&oq=clay+cutter+with+string&gs_l=psy-ab.3...2805.3701.0.3994.6.6.0.0.0.0.107.616.1j5.6.0....0...1c.1.64.psy-ab..0.0.0....0.iIdhAzXwngQ#imgrc=g5SELqXbkl8xPM:), or any of these [clay carvers](https://www.google.co.uk/search?rlz=1C1CHBF_en-GBGB777GB777&biw=681&bih=642&tbm=isch&sa=1&ei=cuSsWviHC4uasAGim7XwCg&q=clay+tools&oq=clay+tools&gs_l=psy-ab.3..0l8.5433.5858.0.6074.5.5.0.0.0.0.170.633.1j4.5.0....0...1c.1.64.psy-ab..0.5.625....0.feMXgGUfAqI#imgrc=LJL95dejHLEbZM:)

**Comment by codetaylor** [comment]
Feature is available in 1.12.2-1.19.0-SNAPSHOT.1

**Comment by Habeeb-M** [comment]
Close issue?

**Comment by codetaylor** [comment]
It will automatically close when commit 13762cc is merged into the main branch. :)

**Comment by codetaylor** [comment]
I'm going to go ahead and close this early, even though it hasn't been merged into the master branch or properly released yet. It is available in the current alpha snapshot and will be in the next beta release.
