### ISSUE TITLE
Configurable board sizes

### ISSUE THREAD

**Issue by Lance5057** [codetaylor/artisan-worktables#94]
It would be nice if the size of the crafting board could be edited, so instead of everything having 3x3 it could be 5x5 or 7x7 or whatever. 
This could allow for example, the blacksmithing table to work more like Kitsu's Forgecraft.

**Comment by Xaikii** [comment]
#29

**Comment by Lance5057** [comment]
Whoops sorry, I had searched for it but couldn't find anything.
