### ISSUE TITLE
ContentTweaker Custom Fluids have Gray Color In Artisan Worktable Tank

### ISSUE THREAD

**Issue by Vyraal1** [codetaylor/artisan-worktables#95]
#### Intro
Hi
#### Issue Description

Custom Fluids made in [my modpack](https://github.com/Vyraal1/Interaction) via ContentTweaker show up as gray in the GUI of Artisan Worktables, see molten rubber below.

#### What Happens

![image](https://user-images.githubusercontent.com/26587049/37845886-5af5ed70-2ea2-11e8-9447-087a8200421c.png)

- bucketing in molten rubber created via ContentTweaker results in a gray texture, it appears black everywhere else

![image](https://user-images.githubusercontent.com/26587049/37845981-9054eef8-2ea2-11e8-91b9-01e5dfe7bef0.png)

#### What You Expect to Happen
Correct color of liquid in the GUI

#### Script

Artisan Worktable Script for Rubber Plates
https://hastebin.com/jobaqecoqa.css

Full Script (See Line 506): https://hastebin.com/qularajabi.xml
ContentTweaker Script (See Line 301):https://hastebin.com/ovewiviseq.cs

#### Affected Versions

* Minecraft: 1.12.2
* Forge: 2631
* CraftTweaker: 1.12-4.1.6
* Artisan Worktables:1.17.1
* Athenaeum:1.13.0

**Comment by codetaylor** [comment]
I'm looking into this now, thanks for the report!

**Comment by codetaylor** [comment]
![image](https://user-images.githubusercontent.com/1240716/37849059-81488fd2-2e93-11e8-8700-7701e3ba1d74.png)

**Comment by codetaylor** [comment]
Fix available in 1.12.2-1.17.2
