### ISSUE TITLE
Crash With Custom Better Builder's Wands recipe

### ISSUE THREAD

**Issue by TheLimePixel** [codetaylor/artisan-worktables#97]
#### What Happens
 So I have a custom recipe for the Stone Wand, from Better Builder's Wands, in the Mage's Worktable. When placing the last item in the crafting grid, the client crashes. After the player logs back in the world, the item, that was placed when the crash ocrured, is gone.

#### What You Expect to Happen
 I expected the recipe to work and no crashes to occur.

#### Script
https://pastebin.com/CgntT8ji

#### Crash Log
https://pastebin.com/HB87NStS

#### Affected Versions
* Minecraft: 1.12.2
* Forge: 14.23.2.2624
* CraftTweaker: 1.12-1.4.5
* Artisan Worktables:1.12.2-1.17.2
* Athenaeum:1.12.2-1.13.0

**Comment by codetaylor** [comment]
It's probably crashing because the last array element only has one item.

It looks at that recipe as a 3x3, but instead it is:

```
XXX
XXX
X
```

Try this instead:

```js
RecipeBuilder.get("mage")
  .setShaped([
  [null,null,<extrautils2:compressedcobblestone>],
  [null,<minecraft:stick>,null],
  [<minecraft:stick>, null, null]
  ])
  .addTool(<ore:artisansGrimoire>, 25)
  .addOutput(<betterbuilderswands:wandstone>)
  .create();
```

**Comment by TheLimePixel** [comment]
Ah, that's why it said index 7 in the crash log. Yet, why don't you make the shaped recipes work like they do in a regular crafting table; allow leaving out elements?
